# -*- coding: utf-8 -*-
"""Age-rating page copy for the Offgrid Media subsite (all 10 locales).

The facts here mirror ../share_to_save/fastlane/metadata/app_rating_config.json
verbatim: unrestrictedWebAccess = true, every content descriptor = NONE. Do not
add a claim the questionnaire does not support.
"""

AGE = {

"en": {
    "nav": "Age rating",
    "title": "Why Offgrid Media is rated 16+ – Age rating",
    "desc": "Offgrid Media is rated 16+ because it can open any web address you give it. The app ships no adult material — and it does not stop you storing or playing any.",
    "h1": "Why Offgrid Media is rated 16+",
    "updated": "Last updated 4 September 2026",
    "body": [
        ("p", "<strong>Offgrid Media is rated 16+ on the App Store.</strong> The rating does not come from anything in the app. It comes from a single answer in Apple's age-rating questionnaire: the app can open a web address you give it, and no address is off limits."),
        ("h2", "What Apple asks, and how the app answers"),
        ("ul", ["<strong>Unrestricted web access — Yes.</strong> Paste a link, or send one from your browser's share sheet, and the app fetches what is at that address. Any address. It does not filter, categorise or check what comes back.",
                "<strong>User-generated content — No.</strong> No feed, no comments, no profiles, no way to publish or send anything to another person.",
                "<strong>Messaging or chat — No.</strong>",
                "<strong>Advertising — No.</strong> No ads, no ad SDKs, no ad identifier.",
                "<strong>Gambling, simulated gambling, loot boxes, contests — None.</strong> The app is free and has none of these.",
                "<strong>Age assurance and in-app parental controls — No.</strong> There is no age gate and no built-in content restriction."]),
        ("h2", "Every content descriptor is None"),
        ("p", "Violence of any kind, sexual content or nudity, mature or suggestive themes, profanity or crude humour, alcohol, tobacco or drug references, horror or fear themes, weapons, medical or treatment information, gambling and contests are all answered <em>None</em> — because the app contains no content at all. There is no catalogue, no library of titles, no recommendations, no store, no editorial. On a fresh install it is empty."),
        ("h2", "The app ships no adult material"),
        ("p", "Nothing adult, suggestive or explicit is shipped with Offgrid Media, offered inside it or made discoverable by it. There is no search over anyone else's material and nothing to browse. Every file in your library is one you put there."),
        ("h2", "But the app does not prevent adult material"),
        ("p", "Offgrid Media plays and stores whatever you give it. Import an adult video from Files or Photos, or add one from a link, and the app will keep it and play it like any other file. It does not inspect, classify, blur or block what you add. It has no content filter, no age gate and no parental mode. That is why 16+ is the honest rating even though the app itself contains nothing."),
        ("p", "Playback is local, and the app has no account and no server. Nothing is uploaded, so there is nothing to moderate, report or review — no one, the developer included, can see what is in your library."),
        ("h2", "What that leaves to you"),
        ("ul", ["Only add content you have the right to keep.",
                "What you store and play is your responsibility under the law where you are.",
                "On a device a child uses, Apple's Screen Time content restrictions can block the app by age rating or prevent it being installed. The app has no restriction of its own to switch on."]),
        ("h2", "If you think the rating is wrong"),
        ("p", 'Write to <a href="mailto:awr9a2npb@mozmail.com">awr9a2npb@mozmail.com</a> and say what you saw. The questionnaire answers above are the ones filed in App Store Connect.'),
    ],
},

"de": {
    "nav": "Altersfreigabe",
    "title": "Warum Offgrid Media ab 16 freigegeben ist – Altersfreigabe",
    "desc": "Offgrid Media ist ab 16 freigegeben, weil die App jede Webadresse öffnen kann, die du ihr gibst. Die App enthält keine Inhalte für Erwachsene — sie hindert dich aber auch nicht daran, welche zu speichern.",
    "h1": "Warum Offgrid Media ab 16 freigegeben ist",
    "updated": "Zuletzt aktualisiert am 4. September 2026",
    "body": [
        ("p", "<strong>Offgrid Media ist im App Store ab 16 Jahren freigegeben.</strong> Diese Einstufung ergibt sich nicht aus Inhalten der App, sondern aus einer einzigen Antwort in Apples Fragebogen zur Altersfreigabe: Die App kann eine Webadresse öffnen, die du ihr gibst — und keine Adresse ist ausgeschlossen."),
        ("h2", "Was Apple fragt und wie die App antwortet"),
        ("ul", ["<strong>Uneingeschränkter Webzugriff — Ja.</strong> Du fügst einen Link ein oder teilst ihn aus dem Browser, und die App lädt, was unter dieser Adresse liegt. Jede Adresse. Sie filtert, kategorisiert oder prüft nicht, was zurückkommt.",
                "<strong>Nutzergenerierte Inhalte — Nein.</strong> Kein Feed, keine Kommentare, keine Profile, keine Möglichkeit, etwas zu veröffentlichen oder an andere zu senden.",
                "<strong>Nachrichten oder Chat — Nein.</strong>",
                "<strong>Werbung — Nein.</strong> Keine Anzeigen, keine Werbe-SDKs, keine Werbe-ID.",
                "<strong>Glücksspiel, simuliertes Glücksspiel, Lootboxen, Gewinnspiele — Nichts davon.</strong> Die App ist kostenlos und enthält nichts dergleichen.",
                "<strong>Altersverifizierung und Jugendschutz in der App — Nein.</strong> Es gibt keine Altersabfrage und keine eingebaute Inhaltssperre."]),
        ("h2", "Alle Inhaltskategorien stehen auf „Keine“"),
        ("p", "Gewalt jeder Art, sexuelle Inhalte oder Nacktheit, anzügliche Themen, Schimpfwörter oder derber Humor, Alkohol, Tabak oder Drogen, Horror- und Angstthemen, Waffen, medizinische Informationen, Glücksspiel und Gewinnspiele sind alle mit <em>Keine</em> beantwortet — weil die App überhaupt keine Inhalte enthält. Kein Katalog, keine Titelsammlung, keine Empfehlungen, kein Store, keine Redaktion. Nach der Installation ist sie leer."),
        ("h2", "Die App liefert keine Inhalte für Erwachsene"),
        ("p", "Mit Offgrid Media wird nichts Anzügliches oder Explizites ausgeliefert, nichts davon in der App angeboten und nichts auffindbar gemacht. Es gibt keine Suche über fremde Inhalte und nichts zum Stöbern. Jede Datei in deiner Mediathek hast du selbst dorthin gelegt."),
        ("h2", "Sie verhindert solche Inhalte aber auch nicht"),
        ("p", "Offgrid Media speichert und spielt, was du ihr gibst. Wenn du ein Video für Erwachsene aus „Dateien“ oder „Fotos“ importierst oder über einen Link hinzufügst, behält die App es und spielt es ab wie jede andere Datei. Sie prüft, klassifiziert, verpixelt oder blockiert nichts. Es gibt keinen Inhaltsfilter, keine Altersabfrage und keinen Elternmodus. Deshalb ist 16+ die ehrliche Einstufung, obwohl die App selbst nichts enthält."),
        ("p", "Die Wiedergabe läuft lokal, und die App hat weder Konto noch Server. Nichts wird hochgeladen, also gibt es nichts zu moderieren, zu melden oder zu prüfen — niemand, auch der Entwickler nicht, kann sehen, was in deiner Mediathek liegt."),
        ("h2", "Was damit bei dir liegt"),
        ("ul", ["Füge nur Inhalte hinzu, die du behalten darfst.",
                "Was du speicherst und abspielst, liegt in deiner Verantwortung nach dem Recht deines Landes.",
                "Auf einem Gerät, das ein Kind nutzt, können Apples Bildschirmzeit-Beschränkungen die App nach Altersfreigabe sperren oder die Installation verhindern. Die App selbst hat keine eigene Sperre, die man einschalten könnte."]),
        ("h2", "Wenn du die Einstufung für falsch hältst"),
        ("p", 'Schreib an <a href="mailto:awr9a2npb@mozmail.com">awr9a2npb@mozmail.com</a> und beschreibe, was dir aufgefallen ist. Die Antworten oben sind genau die, die in App Store Connect hinterlegt sind.'),
    ],
},

"fr": {
    "nav": "Classification d'âge",
    "title": "Pourquoi Offgrid Media est classée 16+ – Classification d'âge",
    "desc": "Offgrid Media est classée 16+ parce qu'elle peut ouvrir n'importe quelle adresse web que vous lui donnez. L'app ne contient aucun contenu pour adultes — et ne vous empêche pas d'en stocker.",
    "h1": "Pourquoi Offgrid Media est classée 16+",
    "updated": "Dernière mise à jour le 4 septembre 2026",
    "body": [
        ("p", "<strong>Offgrid Media est classée 16+ sur l'App Store.</strong> Cette classification ne vient d'aucun contenu de l'app. Elle vient d'une seule réponse au questionnaire d'Apple : l'app peut ouvrir une adresse web que vous lui donnez, et aucune adresse n'est exclue."),
        ("h2", "Ce qu'Apple demande, et ce que répond l'app"),
        ("ul", ["<strong>Accès web sans restriction — Oui.</strong> Vous collez un lien, ou vous le partagez depuis le navigateur, et l'app récupère ce qui se trouve à cette adresse. N'importe laquelle. Elle ne filtre, ne classe et ne vérifie rien.",
                "<strong>Contenu généré par les utilisateurs — Non.</strong> Aucun fil, aucun commentaire, aucun profil, aucun moyen de publier ou d'envoyer quoi que ce soit à quelqu'un.",
                "<strong>Messagerie ou chat — Non.</strong>",
                "<strong>Publicité — Non.</strong> Aucune publicité, aucun SDK publicitaire, aucun identifiant publicitaire.",
                "<strong>Jeux d'argent, simulations, coffres à butin, concours — Aucun.</strong> L'app est gratuite et n'en contient aucun.",
                "<strong>Vérification de l'âge et contrôle parental dans l'app — Non.</strong> Pas de barrière d'âge, pas de restriction de contenu intégrée."]),
        ("h2", "Toutes les catégories de contenu sont sur « Aucun »"),
        ("p", "Violence sous toutes ses formes, contenu sexuel ou nudité, thèmes suggestifs, grossièretés ou humour vulgaire, alcool, tabac ou drogues, horreur et peur, armes, informations médicales, jeux d'argent et concours : tout est répondu <em>Aucun</em> — parce que l'app ne contient aucun contenu. Pas de catalogue, pas de collection de titres, pas de recommandations, pas de boutique, pas d'éditorial. Après l'installation, elle est vide."),
        ("h2", "L'app ne fournit aucun contenu pour adultes"),
        ("p", "Rien de suggestif ni d'explicite n'est livré avec Offgrid Media, proposé à l'intérieur ou rendu trouvable par elle. Il n'y a pas de recherche dans les contenus d'autrui, ni rien à parcourir. Chaque fichier de votre médiathèque est un fichier que vous y avez mis."),
        ("h2", "Mais elle ne l'empêche pas non plus"),
        ("p", "Offgrid Media stocke et lit ce que vous lui donnez. Si vous importez une vidéo pour adultes depuis Fichiers ou Photos, ou l'ajoutez via un lien, l'app la conserve et la lit comme n'importe quel autre fichier. Elle n'inspecte, ne classe, ne floute et ne bloque rien. Aucun filtre de contenu, aucune barrière d'âge, aucun mode parental. C'est pourquoi 16+ est la classification honnête, même si l'app elle-même ne contient rien."),
        ("p", "La lecture est locale et l'app n'a ni compte ni serveur. Rien n'est envoyé, donc il n'y a rien à modérer, à signaler ou à examiner — personne, pas même le développeur, ne peut voir ce que contient votre médiathèque."),
        ("h2", "Ce qui vous revient"),
        ("ul", ["N'ajoutez que des contenus que vous avez le droit de conserver.",
                "Ce que vous stockez et lisez relève de votre responsabilité au regard du droit applicable chez vous.",
                "Sur un appareil utilisé par un enfant, les restrictions Temps d'écran d'Apple peuvent bloquer l'app selon sa classification ou en empêcher l'installation. L'app n'a aucune restriction propre à activer."]),
        ("h2", "Si la classification vous semble erronée"),
        ("p", 'Écrivez à <a href="mailto:awr9a2npb@mozmail.com">awr9a2npb@mozmail.com</a> en décrivant ce que vous avez constaté. Les réponses ci-dessus sont exactement celles déposées dans App Store Connect.'),
    ],
},

"es": {
    "nav": "Clasificación por edad",
    "title": "Por qué Offgrid Media tiene clasificación 16+ – Clasificación por edad",
    "desc": "Offgrid Media tiene clasificación 16+ porque puede abrir cualquier dirección web que le des. La app no incluye contenido para adultos, pero tampoco te impide guardarlo.",
    "h1": "Por qué Offgrid Media tiene clasificación 16+",
    "updated": "Última actualización: 4 de septiembre de 2026",
    "body": [
        ("p", "<strong>Offgrid Media tiene clasificación 16+ en el App Store.</strong> Esa clasificación no procede de ningún contenido de la app, sino de una sola respuesta del cuestionario de Apple: la app puede abrir una dirección web que tú le indiques, y ninguna dirección queda excluida."),
        ("h2", "Qué pregunta Apple y qué responde la app"),
        ("ul", ["<strong>Acceso web sin restricciones — Sí.</strong> Pegas un enlace, o lo compartes desde el navegador, y la app descarga lo que haya en esa dirección. Cualquiera. No filtra, no clasifica ni comprueba lo que recibe.",
                "<strong>Contenido generado por usuarios — No.</strong> No hay muro, ni comentarios, ni perfiles, ni forma de publicar o enviar nada a otra persona.",
                "<strong>Mensajería o chat — No.</strong>",
                "<strong>Publicidad — No.</strong> Sin anuncios, sin SDK publicitarios, sin identificador de publicidad.",
                "<strong>Apuestas, apuestas simuladas, cajas de botín, concursos — Ninguno.</strong> La app es gratuita y no incluye nada de esto.",
                "<strong>Verificación de edad y control parental en la app — No.</strong> No hay barrera de edad ni restricción de contenido integrada."]),
        ("h2", "Todos los descriptores de contenido están en «Ninguno»"),
        ("p", "Violencia de cualquier tipo, contenido sexual o desnudez, temas sugerentes, lenguaje soez o humor grosero, alcohol, tabaco o drogas, terror y miedo, armas, información médica, apuestas y concursos están todos respondidos como <em>Ninguno</em>, porque la app no contiene contenido alguno. No hay catálogo, ni colección de títulos, ni recomendaciones, ni tienda, ni sección editorial. Recién instalada está vacía."),
        ("h2", "La app no incluye material para adultos"),
        ("p", "Con Offgrid Media no se distribuye nada sugerente ni explícito, no se ofrece nada dentro de la app y no se hace localizable nada. No hay búsqueda sobre material ajeno ni nada que explorar. Cada archivo de tu biblioteca lo has puesto tú."),
        ("h2", "Pero tampoco lo impide"),
        ("p", "Offgrid Media guarda y reproduce lo que le des. Si importas un vídeo para adultos desde Archivos o Fotos, o lo añades desde un enlace, la app lo conservará y lo reproducirá como cualquier otro archivo. No inspecciona, clasifica, difumina ni bloquea nada. No tiene filtro de contenido, ni barrera de edad, ni modo parental. Por eso 16+ es la clasificación honesta aunque la app en sí no contenga nada."),
        ("p", "La reproducción es local y la app no tiene cuenta ni servidor. Nada se sube, así que no hay nada que moderar, denunciar o revisar: nadie, tampoco el desarrollador, puede ver qué hay en tu biblioteca."),
        ("h2", "Lo que queda de tu parte"),
        ("ul", ["Añade solo contenido que tengas derecho a conservar.",
                "Lo que guardes y reproduzcas es tu responsabilidad según la ley de tu país.",
                "En un dispositivo que use un menor, las restricciones de Tiempo de Uso de Apple pueden bloquear la app por su clasificación o impedir su instalación. La app no tiene ninguna restricción propia que activar."]),
        ("h2", "Si crees que la clasificación es incorrecta"),
        ("p", 'Escribe a <a href="mailto:awr9a2npb@mozmail.com">awr9a2npb@mozmail.com</a> y cuenta qué has visto. Las respuestas anteriores son exactamente las presentadas en App Store Connect.'),
    ],
},

"pt": {
    "nav": "Classificação etária",
    "title": "Por que o Offgrid Media é classificado 16+ – Classificação etária",
    "desc": "O Offgrid Media é classificado 16+ porque pode abrir qualquer endereço da web que você indicar. O app não traz conteúdo adulto — e também não impede que você guarde algum.",
    "h1": "Por que o Offgrid Media é classificado 16+",
    "updated": "Última atualização: 4 de setembro de 2026",
    "body": [
        ("p", "<strong>O Offgrid Media é classificado 16+ na App Store.</strong> Essa classificação não vem de nada que exista dentro do app. Vem de uma única resposta do questionário da Apple: o app consegue abrir um endereço da web que você indicar, e nenhum endereço fica de fora."),
        ("h2", "O que a Apple pergunta e o que o app responde"),
        ("ul", ["<strong>Acesso irrestrito à web — Sim.</strong> Você cola um link, ou compartilha um a partir do navegador, e o app baixa o que estiver naquele endereço. Qualquer endereço. Ele não filtra, não classifica e não verifica o que chega.",
                "<strong>Conteúdo gerado por usuários — Não.</strong> Sem feed, sem comentários, sem perfis, sem qualquer forma de publicar ou enviar algo a outra pessoa.",
                "<strong>Mensagens ou chat — Não.</strong>",
                "<strong>Publicidade — Não.</strong> Sem anúncios, sem SDKs de publicidade, sem identificador de anúncios.",
                "<strong>Apostas, apostas simuladas, loot boxes, concursos — Nenhum.</strong> O app é gratuito e não tem nada disso.",
                "<strong>Verificação de idade e controle parental no app — Não.</strong> Não há barreira etária nem restrição de conteúdo embutida."]),
        ("h2", "Todos os descritores de conteúdo estão em «Nenhum»"),
        ("p", "Violência de qualquer tipo, conteúdo sexual ou nudez, temas sugestivos, palavrões ou humor grosseiro, álcool, tabaco ou drogas, terror e medo, armas, informações médicas, apostas e concursos estão todos respondidos como <em>Nenhum</em> — porque o app não contém conteúdo algum. Não há catálogo, coleção de títulos, recomendações, loja nem editorial. Recém-instalado, ele está vazio."),
        ("h2", "O app não traz material adulto"),
        ("p", "Nada sugestivo ou explícito é distribuído com o Offgrid Media, oferecido dentro dele ou tornado localizável por ele. Não há busca no material de terceiros e não há nada para navegar. Cada arquivo da sua biblioteca foi você que colocou."),
        ("h2", "Mas ele também não impede"),
        ("p", "O Offgrid Media guarda e reproduz o que você der a ele. Se você importar um vídeo adulto do app Arquivos ou de Fotos, ou adicionar por um link, o app vai guardá-lo e reproduzi-lo como qualquer outro arquivo. Ele não inspeciona, não classifica, não desfoca e não bloqueia nada. Não tem filtro de conteúdo, barreira etária nem modo parental. Por isso 16+ é a classificação honesta, mesmo o app em si não contendo nada."),
        ("p", "A reprodução é local e o app não tem conta nem servidor. Nada é enviado, então não há o que moderar, denunciar ou revisar — ninguém, nem o desenvolvedor, consegue ver o que há na sua biblioteca."),
        ("h2", "O que fica com você"),
        ("ul", ["Adicione apenas conteúdo que você tem o direito de guardar.",
                "O que você guarda e reproduz é responsabilidade sua perante a lei do seu país.",
                "Em um aparelho usado por uma criança, as restrições do Tempo de Uso da Apple podem bloquear o app pela classificação ou impedir a instalação. O app não tem restrição própria para ativar."]),
        ("h2", "Se você acha que a classificação está errada"),
        ("p", 'Escreva para <a href="mailto:awr9a2npb@mozmail.com">awr9a2npb@mozmail.com</a> contando o que viu. As respostas acima são exatamente as registradas no App Store Connect.'),
    ],
},

"id": {
    "nav": "Peringkat usia",
    "title": "Mengapa Offgrid Media berperingkat 16+ – Peringkat usia",
    "desc": "Offgrid Media berperingkat 16+ karena bisa membuka alamat web apa pun yang Anda berikan. Aplikasi ini tidak memuat materi dewasa — dan juga tidak mencegah Anda menyimpannya.",
    "h1": "Mengapa Offgrid Media berperingkat 16+",
    "updated": "Terakhir diperbarui 4 September 2026",
    "body": [
        ("p", "<strong>Offgrid Media berperingkat 16+ di App Store.</strong> Peringkat itu tidak berasal dari isi aplikasi, melainkan dari satu jawaban dalam kuesioner peringkat usia Apple: aplikasi dapat membuka alamat web yang Anda berikan, dan tidak ada alamat yang dikecualikan."),
        ("h2", "Yang ditanyakan Apple, dan jawaban aplikasi"),
        ("ul", ["<strong>Akses web tanpa batas — Ya.</strong> Anda menempel tautan, atau membagikannya dari peramban, lalu aplikasi mengambil apa pun yang ada di alamat itu. Alamat mana pun. Aplikasi tidak menyaring, menggolongkan, atau memeriksa apa yang diterimanya.",
                "<strong>Konten buatan pengguna — Tidak.</strong> Tidak ada linimasa, komentar, profil, atau cara untuk menerbitkan dan mengirim apa pun ke orang lain.",
                "<strong>Pesan atau obrolan — Tidak.</strong>",
                "<strong>Iklan — Tidak.</strong> Tanpa iklan, tanpa SDK iklan, tanpa pengenal iklan.",
                "<strong>Judi, simulasi judi, loot box, undian — Tidak ada.</strong> Aplikasi ini gratis dan tidak memuat satu pun dari itu.",
                "<strong>Verifikasi usia dan kontrol orang tua di aplikasi — Tidak.</strong> Tidak ada gerbang usia dan tidak ada pembatasan konten bawaan."]),
        ("h2", "Semua deskriptor konten bernilai «Tidak ada»"),
        ("p", "Kekerasan dalam bentuk apa pun, konten seksual atau ketelanjangan, tema sugestif, kata kasar atau humor vulgar, alkohol, tembakau atau narkoba, tema horor dan menakutkan, senjata, informasi medis, judi, dan undian semuanya dijawab <em>Tidak ada</em> — karena aplikasi ini memang tidak memuat konten apa pun. Tidak ada katalog, koleksi judul, rekomendasi, toko, maupun kurasi. Setelah dipasang, isinya kosong."),
        ("h2", "Aplikasi tidak menyertakan materi dewasa"),
        ("p", "Tidak ada yang sugestif atau eksplisit yang disertakan bersama Offgrid Media, ditawarkan di dalamnya, atau dibuat mudah ditemukan olehnya. Tidak ada pencarian atas materi milik orang lain dan tidak ada yang bisa dijelajahi. Setiap berkas di pustaka Anda adalah berkas yang Anda masukkan sendiri."),
        ("h2", "Tetapi aplikasi juga tidak mencegahnya"),
        ("p", "Offgrid Media menyimpan dan memutar apa pun yang Anda berikan. Jika Anda mengimpor video dewasa dari Files atau Photos, atau menambahkannya lewat tautan, aplikasi akan menyimpan dan memutarnya seperti berkas lain. Aplikasi tidak memeriksa, menggolongkan, mengaburkan, atau memblokir apa yang Anda tambahkan. Tidak ada penyaring konten, gerbang usia, atau mode orang tua. Itulah sebabnya 16+ adalah peringkat yang jujur, meski aplikasinya sendiri tidak memuat apa-apa."),
        ("p", "Pemutaran berjalan lokal, dan aplikasi tidak punya akun maupun server. Tidak ada yang diunggah, jadi tidak ada yang perlu dimoderasi, dilaporkan, atau ditinjau — tidak ada seorang pun, termasuk pengembang, yang bisa melihat isi pustaka Anda."),
        ("h2", "Yang menjadi tanggung jawab Anda"),
        ("ul", ["Tambahkan hanya konten yang Anda berhak menyimpannya.",
                "Apa yang Anda simpan dan putar adalah tanggung jawab Anda menurut hukum yang berlaku di tempat Anda.",
                "Pada perangkat yang dipakai anak, pembatasan Screen Time Apple dapat memblokir aplikasi berdasarkan peringkat usia atau mencegah pemasangannya. Aplikasi ini tidak punya pembatasan sendiri untuk diaktifkan."]),
        ("h2", "Jika menurut Anda peringkatnya keliru"),
        ("p", 'Kirim surel ke <a href="mailto:awr9a2npb@mozmail.com">awr9a2npb@mozmail.com</a> dan ceritakan apa yang Anda temukan. Jawaban di atas persis seperti yang didaftarkan di App Store Connect.'),
    ],
},

"ru": {
    "nav": "Возрастной рейтинг",
    "title": "Почему у Offgrid Media рейтинг 16+ – Возрастной рейтинг",
    "desc": "У Offgrid Media рейтинг 16+, потому что приложение может открыть любой веб-адрес, который вы ему дадите. Материалов для взрослых в приложении нет — но и хранить их оно не мешает.",
    "h1": "Почему у Offgrid Media рейтинг 16+",
    "updated": "Обновлено 4 сентября 2026 г.",
    "body": [
        ("p", "<strong>В App Store у Offgrid Media возрастной рейтинг 16+.</strong> Он вызван не содержимым приложения, а одним ответом в анкете Apple: приложение может открыть веб-адрес, который вы ему укажете, и никакие адреса не исключены."),
        ("h2", "О чём спрашивает Apple и что отвечает приложение"),
        ("ul", ["<strong>Неограниченный доступ к вебу — да.</strong> Вы вставляете ссылку или делитесь ею из браузера, и приложение скачивает то, что находится по этому адресу. По любому адресу. Оно не фильтрует, не классифицирует и не проверяет полученное.",
                "<strong>Пользовательский контент — нет.</strong> Нет ленты, комментариев, профилей и никакой возможности что-либо опубликовать или отправить другому человеку.",
                "<strong>Сообщения или чат — нет.</strong>",
                "<strong>Реклама — нет.</strong> Ни рекламы, ни рекламных SDK, ни рекламного идентификатора.",
                "<strong>Азартные игры, их имитация, лутбоксы, конкурсы — ничего этого нет.</strong> Приложение бесплатное.",
                "<strong>Проверка возраста и родительский контроль внутри приложения — нет.</strong> Ни возрастного барьера, ни встроенных ограничений контента."]),
        ("h2", "Все категории контента отмечены как «Отсутствует»"),
        ("p", "Насилие любого рода, сексуальный контент или нагота, откровенные темы, брань или грубый юмор, алкоголь, табак и наркотики, ужасы и пугающие темы, оружие, медицинская информация, азартные игры и конкурсы — везде стоит <em>«Отсутствует»</em>, потому что в приложении вообще нет контента. Нет каталога, подборки, рекомендаций, магазина и редакции. После установки оно пустое."),
        ("h2", "Приложение не поставляет материалы для взрослых"),
        ("p", "Вместе с Offgrid Media не поставляется ничего откровенного, ничего такого не предлагается внутри и не делается доступным для поиска. Нет поиска по чужим материалам и нечего просматривать. Каждый файл в вашей медиатеке положили туда вы."),
        ("h2", "Но и не препятствует им"),
        ("p", "Offgrid Media хранит и воспроизводит всё, что вы ему дадите. Импортируете видео для взрослых из «Файлов» или «Фото» либо добавите по ссылке — приложение сохранит и воспроизведёт его, как любой другой файл. Оно не изучает, не классифицирует, не размывает и не блокирует добавленное. Нет ни фильтра контента, ни возрастного барьера, ни родительского режима. Поэтому 16+ — честный рейтинг, хотя само приложение не содержит ничего."),
        ("p", "Воспроизведение локальное, у приложения нет ни аккаунта, ни сервера. Ничего не выгружается, поэтому нечего модерировать, не на что жаловаться и нечего проверять — никто, включая разработчика, не видит содержимое вашей медиатеки."),
        ("h2", "Что остаётся на вас"),
        ("ul", ["Добавляйте только то, что вы вправе хранить.",
                "За то, что вы храните и воспроизводите, отвечаете вы — по законам вашей страны.",
                "На устройстве, которым пользуется ребёнок, ограничения «Экранного времени» Apple могут заблокировать приложение по возрастному рейтингу или запретить его установку. Собственных ограничений, которые можно включить, у приложения нет."]),
        ("h2", "Если считаете рейтинг неверным"),
        ("p", 'Напишите на <a href="mailto:awr9a2npb@mozmail.com">awr9a2npb@mozmail.com</a> и опишите, что вы увидели. Ответы выше — ровно те, что поданы в App Store Connect.'),
    ],
},

"hi": {
    "nav": "आयु रेटिंग",
    "title": "Offgrid Media को 16+ रेटिंग क्यों मिली – आयु रेटिंग",
    "desc": "Offgrid Media की रेटिंग 16+ इसलिए है क्योंकि यह आपका दिया कोई भी वेब पता खोल सकता है। ऐप में वयस्क सामग्री नहीं है — पर यह आपको ऐसी सामग्री रखने से रोकता भी नहीं।",
    "h1": "Offgrid Media को 16+ रेटिंग क्यों मिली",
    "updated": "अंतिम अद्यतन: 4 सितंबर 2026",
    "body": [
        ("p", "<strong>App Store पर Offgrid Media की रेटिंग 16+ है।</strong> यह रेटिंग ऐप की किसी सामग्री से नहीं आती। यह Apple की आयु-रेटिंग प्रश्नावली के एक ही उत्तर से आती है: ऐप आपका दिया हुआ वेब पता खोल सकता है, और कोई भी पता बाहर नहीं है।"),
        ("h2", "Apple क्या पूछता है और ऐप क्या उत्तर देता है"),
        ("ul", ["<strong>अप्रतिबंधित वेब पहुँच — हाँ।</strong> आप कोई लिंक चिपकाते हैं, या ब्राउज़र से साझा करते हैं, और ऐप उस पते पर जो है उसे ले आता है। कोई भी पता। वह न छानता है, न वर्गीकृत करता है, न जाँचता है कि क्या आया।",
                "<strong>उपयोगकर्ता-निर्मित सामग्री — नहीं।</strong> कोई फ़ीड नहीं, टिप्पणियाँ नहीं, प्रोफ़ाइल नहीं, किसी और को कुछ प्रकाशित या भेजने का कोई तरीका नहीं।",
                "<strong>संदेश या चैट — नहीं।</strong>",
                "<strong>विज्ञापन — नहीं।</strong> न विज्ञापन, न विज्ञापन SDK, न विज्ञापन पहचानकर्ता।",
                "<strong>जुआ, नकली जुआ, लूट बॉक्स, प्रतियोगिताएँ — कुछ नहीं।</strong> ऐप निःशुल्क है और इनमें से कुछ भी नहीं रखता।",
                "<strong>आयु सत्यापन और ऐप में अभिभावक नियंत्रण — नहीं।</strong> न आयु द्वार है, न कोई अंतर्निहित सामग्री प्रतिबंध।"]),
        ("h2", "हर सामग्री श्रेणी «कोई नहीं» पर है"),
        ("p", "किसी भी प्रकार की हिंसा, यौन सामग्री या नग्नता, उत्तेजक विषय, अपशब्द या भद्दा हास्य, शराब, तंबाकू या नशीले पदार्थ, डरावने विषय, हथियार, चिकित्सा जानकारी, जुआ और प्रतियोगिताएँ — सब पर उत्तर <em>कोई नहीं</em> है, क्योंकि ऐप में सामग्री है ही नहीं। न कोई कैटलॉग, न शीर्षकों का संग्रह, न सिफ़ारिशें, न स्टोर, न संपादकीय। नई स्थापना पर यह खाली होता है।"),
        ("h2", "ऐप के साथ कोई वयस्क सामग्री नहीं आती"),
        ("p", "Offgrid Media के साथ कुछ भी उत्तेजक या अश्लील न भेजा जाता है, न ऐप के भीतर पेश किया जाता है, न खोजने योग्य बनाया जाता है। दूसरों की सामग्री में खोज नहीं है और देखने-भर को कुछ नहीं है। आपकी लाइब्रेरी की हर फ़ाइल वही है जो आपने डाली।"),
        ("h2", "पर ऐप ऐसी सामग्री रोकता भी नहीं"),
        ("p", "Offgrid Media वही रखता और चलाता है जो आप उसे देते हैं। यदि आप Files या Photos से कोई वयस्क वीडियो आयात करते हैं, या किसी लिंक से जोड़ते हैं, तो ऐप उसे बाकी फ़ाइलों की तरह रखेगा और चलाएगा। वह जाँचता, वर्गीकृत, धुँधला या अवरुद्ध कुछ नहीं करता। न सामग्री फ़िल्टर है, न आयु द्वार, न अभिभावक मोड। इसीलिए 16+ ईमानदार रेटिंग है, भले ही ऐप में स्वयं कुछ न हो।"),
        ("p", "प्लेबैक स्थानीय है और ऐप का न कोई खाता है, न सर्वर। कुछ अपलोड नहीं होता, इसलिए न कुछ मॉडरेट करने को है, न रिपोर्ट करने को, न समीक्षा करने को — डेवलपर सहित कोई नहीं देख सकता कि आपकी लाइब्रेरी में क्या है।"),
        ("h2", "जो आपके ज़िम्मे रहता है"),
        ("ul", ["केवल वही सामग्री जोड़ें जिसे रखने का आपको अधिकार है।",
                "आप जो रखते और चलाते हैं, वह आपके यहाँ लागू कानून के अनुसार आपकी ज़िम्मेदारी है।",
                "जिस डिवाइस का उपयोग बच्चा करता हो, वहाँ Apple की Screen Time पाबंदियाँ ऐप को आयु रेटिंग के आधार पर रोक सकती हैं या स्थापना ही न होने दें। ऐप के पास चालू करने योग्य अपनी कोई पाबंदी नहीं है।"]),
        ("h2", "यदि आपको रेटिंग ग़लत लगे"),
        ("p", '<a href="mailto:awr9a2npb@mozmail.com">awr9a2npb@mozmail.com</a> पर लिखें और बताएँ कि आपने क्या देखा। ऊपर दिए उत्तर ठीक वही हैं जो App Store Connect में दर्ज हैं।'),
    ],
},

"ar": {
    "nav": "التصنيف العمري",
    "title": "لماذا تصنيف Offgrid Media هو ‎16+‎ – التصنيف العمري",
    "desc": "تصنيف Offgrid Media هو ‎16+‎ لأنه يستطيع فتح أي عنوان ويب تعطيه إياه. التطبيق لا يتضمّن أي محتوى للبالغين، لكنه أيضًا لا يمنعك من حفظ مثل هذا المحتوى.",
    "h1": "لماذا تصنيف Offgrid Media هو ‎16+‎",
    "updated": "آخر تحديث في 4 سبتمبر 2026",
    "body": [
        ("p", "<strong>تصنيف Offgrid Media في App Store هو ‎16+‎.</strong> هذا التصنيف لا يأتي من أي محتوى داخل التطبيق، بل من إجابة واحدة في استبيان آبل للتصنيف العمري: يستطيع التطبيق فتح عنوان ويب تعطيه إياه، ولا يُستثنى أي عنوان."),
        ("h2", "ما تسأل عنه آبل وما يجيب به التطبيق"),
        ("ul", ["<strong>وصول غير مقيّد إلى الويب — نعم.</strong> تلصق رابطًا، أو تشاركه من المتصفح، فيجلب التطبيق ما يوجد في ذلك العنوان. أي عنوان. وهو لا يصفّي ولا يصنّف ولا يفحص ما يصله.",
                "<strong>محتوى من إنشاء المستخدمين — لا.</strong> لا تدفق منشورات ولا تعليقات ولا ملفات شخصية ولا وسيلة لنشر شيء أو إرساله إلى شخص آخر.",
                "<strong>الرسائل أو الدردشة — لا.</strong>",
                "<strong>الإعلانات — لا.</strong> لا إعلانات ولا حِزم إعلانية ولا معرّف إعلاني.",
                "<strong>القمار ومحاكاته وصناديق الغنائم والمسابقات — لا شيء من ذلك.</strong> التطبيق مجاني ولا يتضمّن أيًّا منها.",
                "<strong>التحقق من العمر والرقابة الأبوية داخل التطبيق — لا.</strong> لا توجد بوابة عمرية ولا قيود محتوى مدمجة."]),
        ("h2", "كل فئات المحتوى مضبوطة على «لا شيء»"),
        ("p", "العنف بجميع أشكاله، والمحتوى الجنسي أو العري، والمواضيع الموحية، والألفاظ النابية أو الفكاهة الفجّة، والكحول والتبغ والمخدرات، ومواضيع الرعب والخوف، والأسلحة، والمعلومات الطبية، والقمار والمسابقات — كلها مُجابة بـ<em>لا شيء</em>، لأن التطبيق لا يحتوي على أي محتوى أصلًا. لا كتالوج ولا مجموعة عناوين ولا توصيات ولا متجر ولا محتوى تحريري. وهو فارغ عند التثبيت."),
        ("h2", "التطبيق لا يتضمّن مواد للبالغين"),
        ("p", "لا يُشحن مع Offgrid Media أي شيء موحٍ أو صريح، ولا يُعرض داخله، ولا يجعله قابلًا للاكتشاف. لا يوجد بحث في مواد الآخرين ولا شيء لتصفّحه. كل ملف في مكتبتك وضعته أنت."),
        ("h2", "لكنه لا يمنعها أيضًا"),
        ("p", "يحفظ Offgrid Media ويشغّل ما تعطيه إياه. إن استوردت مقطعًا للبالغين من «الملفات» أو «الصور»، أو أضفته عبر رابط، فسيحتفظ به التطبيق ويشغّله كأي ملف آخر. وهو لا يفحص ولا يصنّف ولا يطمس ولا يحجب ما تضيفه. لا مرشّح محتوى ولا بوابة عمرية ولا وضع أبوي. لذلك فإن ‎16+‎ هو التصنيف الأمين رغم أن التطبيق نفسه لا يحتوي على شيء."),
        ("p", "التشغيل محلي، ولا حساب للتطبيق ولا خادم. لا شيء يُرفع، فلا شيء يُراقَب أو يُبلَّغ عنه أو يُراجَع — لا أحد، بما في ذلك المطوّر، يمكنه رؤية ما في مكتبتك."),
        ("h2", "ما يبقى على عاتقك"),
        ("ul", ["أضف فقط المحتوى الذي يحق لك الاحتفاظ به.",
                "ما تحفظه وتشغّله مسؤوليتك أنت وفق القانون في مكانك.",
                "على جهاز يستخدمه طفل، يمكن لقيود «مدة استخدام الجهاز» من آبل حجب التطبيق بحسب تصنيفه العمري أو منع تثبيته. فالتطبيق لا يملك قيدًا خاصًا به يمكن تفعيله."]),
        ("h2", "إذا رأيت أن التصنيف غير صحيح"),
        ("p", 'راسل <a href="mailto:awr9a2npb@mozmail.com">awr9a2npb@mozmail.com</a> واذكر ما رأيته. الإجابات أعلاه هي نفسها المسجّلة في App Store Connect.'),
    ],
},

"zh": {
    "nav": "年龄分级",
    "title": "Offgrid Media 为什么分级为 16+ – 年龄分级",
    "desc": "Offgrid Media 分级为 16+，因为它可以打开您给出的任何网址。应用本身不含成人内容，但也不会阻止您存放和播放此类内容。",
    "h1": "Offgrid Media 为什么分级为 16+",
    "updated": "最后更新于 2026 年 9 月 4 日",
    "body": [
        ("p", "<strong>Offgrid Media 在 App Store 的分级是 16+。</strong>这个分级与应用里的任何内容无关，只源于 Apple 年龄分级问卷中的一个答案：应用可以打开您给出的网址，而且不限制是哪一个网址。"),
        ("h2", "Apple 的提问，以及应用的回答"),
        ("ul", ["<strong>不受限的网页访问 —— 是。</strong>您粘贴一个链接，或从浏览器分享过来，应用就会取回该地址上的内容。任何地址都可以。它不做过滤、不做归类，也不检查取回了什么。",
                "<strong>用户生成内容 —— 否。</strong>没有信息流、没有评论、没有个人资料，也没有任何把内容发布或发送给他人的途径。",
                "<strong>消息或聊天 —— 否。</strong>",
                "<strong>广告 —— 否。</strong>没有广告、没有广告 SDK、没有广告标识符。",
                "<strong>博彩、模拟博彩、战利品箱、抽奖 —— 均无。</strong>应用免费，且不含上述任何一项。",
                "<strong>年龄验证与应用内家长控制 —— 否。</strong>没有年龄门槛，也没有内置的内容限制。"]),
        ("h2", "所有内容类别均为「无」"),
        ("p", "各类暴力、性内容或裸露、暗示性主题、脏话或粗俗幽默、烟酒与毒品、恐怖与惊吓主题、武器、医疗信息、博彩与抽奖，全部答为<em>无</em> —— 因为应用根本不含任何内容。没有片库、没有片单、没有推荐、没有商店、没有编辑内容。刚装好时它是空的。"),
        ("h2", "应用不附带成人内容"),
        ("p", "Offgrid Media 不随附任何暗示性或露骨内容，应用内不提供此类内容，也不会让它变得可被发现。没有针对他人内容的搜索，也没有可供浏览的东西。媒体库中的每个文件都是您自己放进去的。"),
        ("h2", "但应用也不会阻止成人内容"),
        ("p", "您给 Offgrid Media 什么，它就存什么、播什么。如果您从「文件」或「照片」导入一个成人视频，或通过链接添加，应用会像对待其他文件一样保存并播放它。它不会检查、归类、模糊或屏蔽您添加的内容，没有内容过滤、没有年龄门槛，也没有家长模式。正因如此，尽管应用本身不含任何内容，16+ 仍是诚实的分级。"),
        ("p", "播放在本地进行，应用没有账户也没有服务器。没有任何内容被上传，因此没有什么可审核、可举报、可复查 —— 包括开发者在内，没有人能看到您的媒体库里有什么。"),
        ("h2", "余下的责任在您"),
        ("ul", ["请仅添加您有权保存的内容。",
                "您所存放和播放的内容，依您所在地的法律由您自行负责。",
                "在儿童使用的设备上，Apple 的「屏幕使用时间」限制可按年龄分级屏蔽本应用或阻止安装。应用自身没有可开启的限制功能。"]),
        ("h2", "如果您认为分级有误"),
        ("p", '请写信至 <a href="mailto:awr9a2npb@mozmail.com">awr9a2npb@mozmail.com</a>，说明您看到的情况。上述答案与提交至 App Store Connect 的完全一致。'),
    ],
},

}
