# -*- coding: utf-8 -*-
"""UI strings for the Offgrid Media subsite.

Marketing claims (lede, feature blocks, rights notice) are NOT here — they come
from the app's App Store metadata at build time. Only site chrome lives here.
"""
from strings_b import STRINGS_B

STRINGS = {

"en": {
    "feature_heads": [
        "Import from Files and Photos",
        "Organise it your way",
        "Built for offline",
        "A real player",
        "Background audio",
        "Choose your quality",
        "No account. No ads. No tracking.",
    ],
    "meta_title": "Offgrid Media – Your Personal Offline Media Library for iPhone & iPad",
    "meta_desc": "Offgrid Media is a private media library for iPhone and iPad. Import video and audio from Files or Photos, organise it into folders, and play everything offline. No account, no ads, no tracking.",
    "og_title": "Offgrid Media – Your Personal Offline Media Library",
    "og_desc": "Import video and audio from Files or Photos, organise it into folders, and play it all offline. On device. No account.",
    "og_image_alt": "Offgrid Media – Everything you keep, offline",
    "currency": "USD",
    "nav_library": "The library", "nav_features": "Features", "nav_privacy": "Privacy",
    "nav_faq": "FAQ", "nav_overview": "Overview",
    "nav_toggle": "Toggle navigation", "theme_toggle": "Toggle theme",
    "footer_nav": "Footer", "device": "Device",
    "h1": "Everything you keep,|offline.",
    "cta_soon": "Coming to the App Store", "cta_meta": "Free · iPhone & iPad",
    "cta_meta2": "Free · iOS 16.1+", "cta_secondary": "See how it works",
    "cta_live": "Download on the App Store",
    "switch_off": "Airplane mode on", "switch_on": "Airplane mode off",
    "hint_off": "Try it. The grid is off — your library plays anyway.",
    "hint_on": "Grid back on. Nothing about your library changed.",
    "chip_network": "Network", "chip_no_conn": "No connection", "chip_conn": "Connected",
    "chip_library": "Your library", "chip_playing": "Playing",
    "chip_caption": "Same on both settings. That is the whole idea.",
    "video_label": "Offgrid Media app preview: importing, organising and playing an offline media library",
    "lbl_library": "The library",
    "h2_library": "One tidy place for the media you own",
    "sub_library": "Folders, search, and a filter for video or audio. Thumbnails come from the file itself, album art and metadata are preserved.",
    "lbl_how": "How it works", "h2_how": "Import, organise, play",
    "lbl_features": "What it does",
    "h2_features": "A real player, not a folder of files",
    "sub_features": "Everything below works with the network off.",
    "h2_privacy": "Nothing to collect, because there is nowhere to send it",
    "sub_privacy": "Offgrid Media has no account and no server of its own. Its App Store privacy manifest declares no tracking and no collected data types.",
    "privacy_items": [
        ("No account", "No sign-up, no login, no profile. Open the app and it works."),
        ("No analytics in the app", "No tracking SDKs, no crash reporters, no advertising frameworks."),
        ("No cloud sync", "Your library is not uploaded anywhere. There is no iCloud sync and no backup service."),
        ("One permission", "Notifications, so the app can tell you when an import finished. That is the only one it asks for."),
    ],
    "privacy_link": "Read the full privacy policy",
    "lbl_faq": "Questions", "h2_faq": "Frequently asked",
    "faq": [
        ("Does Offgrid Media need an internet connection?",
         "No. Once something is in your library it lives on your device and plays with the network off. Nothing is streamed at playback time, so there is no buffering and no connection to lose."),
        ("Where are my files stored?",
         "In a folder on your device, inside the app's own storage. You can pick a different library folder in Settings, and because the app supports the iOS Files app, you can browse the same files there. Nothing is uploaded and there is no cloud sync."),
        ("How do I get media into the library?",
         "Import from Files (iCloud Drive or on-device), import from your photo library, or add from a link you have the right to keep. Import is the main path; adding from a link is a secondary convenience."),
        ("Can it keep playing audio in the background?",
         "Yes. Turn on background audio in Settings and playback continues when you switch apps or lock your screen, with title, artwork and controls on the Lock Screen and in Control Center. Video can float over other apps with Picture in Picture."),
        ("Does the app collect any data?",
         "No. Offgrid Media has no account, no backend, no analytics and no third-party SDKs. Its App Store privacy manifest declares no tracking and no collected data types. The only permission it asks for is notifications."),
        ("What does Offgrid Media cost?",
         "It is free. No subscription, no in-app purchases, no ads."),
    ],
    "close_h2": "Your library. Your device. No signal required.",
    "close_p": "Offgrid Media is free, for iPhone and iPad, in 11 languages.",
    "close_meta": "No account · No ads · No tracking",
    "stat_langs": "Languages", "stat_zero": "Accounts, ads, trackers",
    "stat_device": "On device", "stat_ios": "iOS, iPhone & iPad",
    "privacy_title": "Privacy Policy – Offgrid Media",
    "privacy_desc": "Offgrid Media collects no personal data. No account, no analytics, no third-party SDKs, no cloud sync — everything stays on your device.",
    "privacy_h1": "Privacy policy",
    "privacy_updated": "Last updated 1 August 2026",
    "privacy_back": "Back to Offgrid Media",
    "policy": [
        ("p", "<strong>Offgrid Media does not collect, store or transmit any personal data.</strong> There is no account, no backend service, and no analytics. Your library is a set of files on your device, and it stays there."),
        ("h2", "What the app collects"),
        ("p", "Nothing. The app's App Store privacy manifest declares no tracking and no collected data types. There are no advertising identifiers, no crash reporting services, and no third-party analytics or marketing SDKs in the app."),
        ("h2", "Where your media lives"),
        ("ul", ["Everything you import is written to a folder on your device. You can choose which folder in Settings.",
                "The app supports the iOS Files app, so you can browse and manage the same files yourself.",
                "There is no cloud sync and no upload of any kind. If you pick a folder that iCloud Drive syncs, that syncing is done by Apple under your own iCloud settings, not by the app."]),
        ("h2", "When the app uses the network"),
        ("ul", ["<strong>Playback never uses the network.</strong> Files play from local storage.",
                "<strong>Adding from a link does.</strong> If you paste or share a link, the app contacts that address and the media server it points to, over HTTPS, to fetch the file. Nothing about that request is sent to the developer.",
                "<strong>Links you tap in Settings</strong> open in your browser as normal."]),
        ("h2", "Permissions"),
        ("p", "The app asks for one permission: notifications, so it can tell you when an import finished or failed. You can decline it and the app still works. Importing from Photos uses the standard iOS photo picker, which runs outside the app and requires no photo library access."),
        ("h2", "Diagnostics"),
        ("p", "Settings contains a local activity log to help you see what the app did. It never leaves your device and entries are deleted automatically after two days."),
        ("h2", "Children"),
        ("p", "The app is rated 4+ and collects no data from anyone, including children."),
        ("h2", "This website"),
        ("p", 'Separate from the app: lorenzmaierhofer.com uses <a href="https://plausible.io/privacy-focused-web-analytics" target="_blank" rel="noopener">Plausible Analytics</a> for aggregate page-view statistics. Plausible sets no cookies and collects no personal data. This applies to the website only — the app itself contains no analytics whatsoever.'),
        ("h2", "Content you add"),
        ("p", "Please only add content you have the right to keep. Compliance with the terms of service of any platform and with applicable laws is solely your responsibility."),
        ("h2", "Changes"),
        ("p", "If this policy changes, the updated version will be published on this page with a new date."),
        ("h2", "Contact"),
        ("p", 'Questions about privacy: <a href="mailto:awr9a2npb@mozmail.com">awr9a2npb@mozmail.com</a>'),
    ],
},

"de": {
    "feature_heads": [
        "Import aus Dateien und Fotos",
        "Ordne es nach deinem System",
        "Für offline gemacht",
        "Ein echter Player",
        "Hintergrundwiedergabe",
        "Wähle deine Qualität",
        "Kein Konto. Keine Werbung. Kein Tracking.",
    ],
    "meta_title": "Offgrid Media – Deine private Offline-Mediathek für iPhone & iPad",
    "meta_desc": "Offgrid Media ist eine private Mediathek für iPhone und iPad. Videos und Audios aus Dateien oder Fotos importieren, in Ordner sortieren und alles offline abspielen. Kein Konto, keine Werbung, kein Tracking.",
    "og_title": "Offgrid Media – Deine private Offline-Mediathek",
    "og_desc": "Videos und Audios aus Dateien oder Fotos importieren, in Ordner sortieren und alles offline abspielen. Auf dem Gerät. Ohne Konto.",
    "og_image_alt": "Offgrid Media – Alles, was du behältst, offline",
    "currency": "EUR",
    "nav_library": "Mediathek", "nav_features": "Funktionen", "nav_privacy": "Datenschutz",
    "nav_faq": "FAQ", "nav_overview": "Überblick",
    "nav_toggle": "Navigation umschalten", "theme_toggle": "Design umschalten",
    "footer_nav": "Fußzeile", "device": "Gerät",
    "h1": "Alles, was du behältst,|offline.",
    "cta_soon": "Bald im App Store", "cta_meta": "Kostenlos · iPhone & iPad",
    "cta_meta2": "Kostenlos · iOS 16.1+", "cta_secondary": "So funktioniert es",
    "cta_live": "Im App Store laden",
    "switch_off": "Flugmodus an", "switch_on": "Flugmodus aus",
    "hint_off": "Probier es aus. Das Netz ist weg — deine Mediathek spielt trotzdem.",
    "hint_on": "Netz wieder da. An deiner Mediathek ändert das nichts.",
    "chip_network": "Netz", "chip_no_conn": "Keine Verbindung", "chip_conn": "Verbunden",
    "chip_library": "Deine Mediathek", "chip_playing": "Spielt",
    "chip_caption": "In beiden Fällen gleich. Genau darum geht es.",
    "video_label": "Vorschau von Offgrid Media: importieren, ordnen und offline abspielen",
    "lbl_library": "Die Mediathek",
    "h2_library": "Ein aufgeräumter Ort für deine eigenen Medien",
    "sub_library": "Ordner, Suche und ein Filter für Video oder Audio. Vorschaubilder kommen aus der Datei selbst, Cover und Metadaten bleiben erhalten.",
    "lbl_how": "So funktioniert es", "h2_how": "Importieren, ordnen, abspielen",
    "lbl_features": "Was sie kann",
    "h2_features": "Ein echter Player, kein Ordner voller Dateien",
    "sub_features": "Alles hier unten funktioniert ohne Netz.",
    "h2_privacy": "Nichts zu sammeln, weil es nirgendwohin geht",
    "sub_privacy": "Offgrid Media hat kein Konto und keinen eigenen Server. Das App-Store-Datenschutzmanifest weist kein Tracking und keine erfassten Datentypen aus.",
    "privacy_items": [
        ("Kein Konto", "Keine Registrierung, kein Login, kein Profil. App öffnen, fertig."),
        ("Keine Analyse in der App", "Keine Tracking-SDKs, keine Absturzberichte, keine Werbe-Frameworks."),
        ("Keine Cloud-Synchronisierung", "Deine Mediathek wird nirgendwo hochgeladen. Es gibt keine iCloud-Synchronisierung und keinen Backup-Dienst."),
        ("Eine Berechtigung", "Mitteilungen, damit die App dir sagen kann, wenn ein Import fertig ist. Mehr fragt sie nicht ab."),
    ],
    "privacy_link": "Vollständige Datenschutzerklärung lesen",
    "lbl_faq": "Fragen", "h2_faq": "Häufige Fragen",
    "faq": [
        ("Braucht Offgrid Media eine Internetverbindung?",
         "Nein. Was einmal in deiner Mediathek ist, liegt auf deinem Gerät und spielt auch ohne Netz. Beim Abspielen wird nichts gestreamt, also gibt es kein Puffern und keine Verbindung, die abbrechen kann."),
        ("Wo werden meine Dateien gespeichert?",
         "In einem Ordner auf deinem Gerät, im Speicher der App. In den Einstellungen kannst du einen anderen Mediathek-Ordner wählen, und da die App die Dateien-App unterstützt, kannst du dieselben Dateien auch dort ansehen. Nichts wird hochgeladen, es gibt keine Cloud-Synchronisierung."),
        ("Wie kommen Medien in die Mediathek?",
         "Import aus Dateien (iCloud Drive oder lokal), Import aus der Fotomediathek oder über einen Link, den du behalten darfst. Der Import ist der Hauptweg; der Link ist eine zusätzliche Bequemlichkeit."),
        ("Läuft Audio im Hintergrund weiter?",
         "Ja. Aktiviere Hintergrundwiedergabe in den Einstellungen, dann läuft die Wiedergabe weiter, wenn du die App wechselst oder den Bildschirm sperrst — mit Titel, Cover und Steuerung auf dem Sperrbildschirm und im Kontrollzentrum. Videos laufen im Bild-in-Bild-Modus über anderen Apps weiter."),
        ("Sammelt die App Daten?",
         "Nein. Offgrid Media hat kein Konto, kein Backend, keine Analyse und keine Drittanbieter-SDKs. Das App-Store-Datenschutzmanifest weist kein Tracking und keine erfassten Datentypen aus. Die einzige Berechtigung, die sie anfragt, sind Mitteilungen."),
        ("Was kostet Offgrid Media?",
         "Nichts. Kein Abo, keine In-App-Käufe, keine Werbung."),
    ],
    "close_h2": "Deine Mediathek. Dein Gerät. Kein Empfang nötig.",
    "close_p": "Offgrid Media ist kostenlos, für iPhone und iPad, in 11 Sprachen.",
    "close_meta": "Kein Konto · Keine Werbung · Kein Tracking",
    "stat_langs": "Sprachen", "stat_zero": "Konten, Werbung, Tracker",
    "stat_device": "Auf dem Gerät", "stat_ios": "iOS, iPhone & iPad",
    "privacy_title": "Datenschutzerklärung – Offgrid Media",
    "privacy_desc": "Offgrid Media erfasst keine personenbezogenen Daten. Kein Konto, keine Analyse, keine Drittanbieter-SDKs, keine Cloud-Synchronisierung.",
    "privacy_h1": "Datenschutzerklärung",
    "privacy_updated": "Zuletzt aktualisiert am 1. August 2026",
    "privacy_back": "Zurück zu Offgrid Media",
    "policy": [
        ("p", "<strong>Offgrid Media erfasst, speichert und überträgt keine personenbezogenen Daten.</strong> Es gibt kein Konto, keinen Backend-Dienst und keine Analyse. Deine Mediathek besteht aus Dateien auf deinem Gerät, und dort bleiben sie."),
        ("h2", "Was die App erfasst"),
        ("p", "Nichts. Das App-Store-Datenschutzmanifest der App weist kein Tracking und keine erfassten Datentypen aus. Es gibt keine Werbe-IDs, keine Absturzberichtsdienste und keine Analyse- oder Marketing-SDKs von Drittanbietern in der App."),
        ("h2", "Wo deine Medien liegen"),
        ("ul", ["Alles, was du importierst, wird in einen Ordner auf deinem Gerät geschrieben. Welchen, wählst du in den Einstellungen.",
                "Die App unterstützt die Dateien-App, du kannst dieselben Dateien also selbst ansehen und verwalten.",
                "Es gibt keine Cloud-Synchronisierung und keinen Upload. Wählst du einen Ordner, den iCloud Drive synchronisiert, erfolgt diese Synchronisierung durch Apple nach deinen eigenen iCloud-Einstellungen, nicht durch die App."]),
        ("h2", "Wann die App das Netz nutzt"),
        ("ul", ["<strong>Die Wiedergabe nutzt nie das Netz.</strong> Dateien werden lokal abgespielt.",
                "<strong>Das Hinzufügen über einen Link schon.</strong> Wenn du einen Link einfügst oder teilst, kontaktiert die App diese Adresse und den Medienserver dahinter über HTTPS, um die Datei zu laden. Nichts davon wird an den Entwickler gesendet.",
                "<strong>Links in den Einstellungen</strong> öffnen sich wie gewohnt im Browser."]),
        ("h2", "Berechtigungen"),
        ("p", "Die App fragt eine Berechtigung ab: Mitteilungen, um dir zu sagen, wenn ein Import fertig ist oder fehlgeschlagen ist. Du kannst sie ablehnen, die App funktioniert trotzdem. Der Import aus Fotos nutzt die Standard-Fotoauswahl von iOS, die außerhalb der App läuft und keinen Zugriff auf die Fotomediathek benötigt."),
        ("h2", "Diagnose"),
        ("p", "In den Einstellungen gibt es ein lokales Aktivitätsprotokoll, damit du siehst, was die App getan hat. Es verlässt nie dein Gerät und Einträge werden nach zwei Tagen automatisch gelöscht."),
        ("h2", "Kinder"),
        ("p", "Die App ist ab 4 Jahren freigegeben und erfasst von niemandem Daten, auch nicht von Kindern."),
        ("h2", "Diese Website"),
        ("p", 'Getrennt von der App: lorenzmaierhofer.com nutzt <a href="https://plausible.io/privacy-focused-web-analytics" target="_blank" rel="noopener">Plausible Analytics</a> für aggregierte Seitenaufrufstatistiken. Plausible setzt keine Cookies und erfasst keine personenbezogenen Daten. Das gilt nur für die Website — die App selbst enthält keinerlei Analyse.'),
        ("h2", "Inhalte, die du hinzufügst"),
        ("p", "Bitte füge nur Inhalte hinzu, die du behalten darfst. Die Einhaltung der Nutzungsbedingungen jeder Plattform und der geltenden Gesetze liegt allein in deiner Verantwortung."),
        ("h2", "Änderungen"),
        ("p", "Wenn sich diese Erklärung ändert, wird die aktualisierte Fassung mit neuem Datum auf dieser Seite veröffentlicht."),
        ("h2", "Kontakt"),
        ("p", 'Fragen zum Datenschutz: <a href="mailto:awr9a2npb@mozmail.com">awr9a2npb@mozmail.com</a>'),
    ],
},

"fr": {
    "feature_heads": [
        "Importez depuis Fichiers et Photos",
        "Organisez à votre façon",
        "Conçu pour le hors ligne",
        "Un vrai lecteur",
        "Audio en arrière-plan",
        "Choisissez votre qualité",
        "Aucun compte. Aucune pub. Aucun suivi.",
    ],
    "meta_title": "Offgrid Media – Votre médiathèque hors ligne pour iPhone et iPad",
    "meta_desc": "Offgrid Media est une médiathèque privée pour iPhone et iPad. Importez vidéos et audios depuis Fichiers ou Photos, classez-les en dossiers et lisez tout hors ligne. Aucun compte, aucune pub, aucun suivi.",
    "og_title": "Offgrid Media – Votre médiathèque personnelle hors ligne",
    "og_desc": "Importez vidéos et audios depuis Fichiers ou Photos, classez-les en dossiers et lisez tout hors ligne. Sur l'appareil. Sans compte.",
    "og_image_alt": "Offgrid Media – Tout ce que vous gardez, hors ligne",
    "currency": "EUR",
    "nav_library": "La médiathèque", "nav_features": "Fonctionnalités", "nav_privacy": "Confidentialité",
    "nav_faq": "FAQ", "nav_overview": "Aperçu",
    "nav_toggle": "Afficher la navigation", "theme_toggle": "Changer de thème",
    "footer_nav": "Pied de page", "device": "Appareil",
    "h1": "Tout ce que vous gardez,|hors ligne.",
    "cta_soon": "Bientôt sur l'App Store", "cta_meta": "Gratuit · iPhone et iPad",
    "cta_meta2": "Gratuit · iOS 16.1+", "cta_secondary": "Voir comment ça marche",
    "cta_live": "Télécharger dans l'App Store",
    "switch_off": "Mode avion activé", "switch_on": "Mode avion désactivé",
    "hint_off": "Essayez. Le réseau est coupé — votre médiathèque continue de jouer.",
    "hint_on": "Réseau rétabli. Rien n'a changé pour votre médiathèque.",
    "chip_network": "Réseau", "chip_no_conn": "Aucune connexion", "chip_conn": "Connecté",
    "chip_library": "Votre médiathèque", "chip_playing": "Lecture en cours",
    "chip_caption": "Identique dans les deux cas. C'est tout l'intérêt.",
    "video_label": "Aperçu d'Offgrid Media : importer, organiser et lire hors ligne",
    "lbl_library": "La médiathèque",
    "h2_library": "Un seul endroit bien rangé pour vos médias",
    "sub_library": "Dossiers, recherche et filtre vidéo ou audio. Les vignettes proviennent du fichier lui-même, les pochettes et les métadonnées sont conservées.",
    "lbl_how": "Comment ça marche", "h2_how": "Importer, organiser, lire",
    "lbl_features": "Ce qu'elle fait",
    "h2_features": "Un vrai lecteur, pas un dossier de fichiers",
    "sub_features": "Tout ce qui suit fonctionne sans réseau.",
    "h2_privacy": "Rien à collecter, puisqu'il n'y a nulle part où l'envoyer",
    "sub_privacy": "Offgrid Media n'a ni compte ni serveur. Son manifeste de confidentialité App Store déclare aucun suivi et aucune donnée collectée.",
    "privacy_items": [
        ("Aucun compte", "Pas d'inscription, pas de connexion, pas de profil. Ouvrez l'app, c'est tout."),
        ("Aucune analyse dans l'app", "Aucun SDK de suivi, aucun rapport de plantage, aucun cadre publicitaire."),
        ("Aucune synchronisation cloud", "Votre médiathèque n'est envoyée nulle part. Ni synchronisation iCloud, ni service de sauvegarde."),
        ("Une seule autorisation", "Les notifications, pour vous prévenir quand un import se termine. C'est la seule demandée."),
    ],
    "privacy_link": "Lire la politique de confidentialité complète",
    "lbl_faq": "Questions", "h2_faq": "Questions fréquentes",
    "faq": [
        ("Offgrid Media a-t-elle besoin d'une connexion Internet ?",
         "Non. Une fois dans votre médiathèque, un élément réside sur votre appareil et se lit sans réseau. Rien n'est diffusé en streaming à la lecture : aucune mise en mémoire tampon, aucune connexion à perdre."),
        ("Où mes fichiers sont-ils stockés ?",
         "Dans un dossier sur votre appareil, au sein du stockage de l'app. Vous pouvez choisir un autre dossier dans les Réglages, et comme l'app prend en charge l'app Fichiers, vous pouvez y consulter les mêmes fichiers. Rien n'est téléversé et il n'y a aucune synchronisation cloud."),
        ("Comment ajouter des médias à la médiathèque ?",
         "Import depuis Fichiers (iCloud Drive ou appareil), import depuis votre photothèque, ou ajout via un lien que vous avez le droit de conserver. L'import est la voie principale ; le lien n'est qu'une commodité secondaire."),
        ("L'audio continue-t-il en arrière-plan ?",
         "Oui. Activez l'audio en arrière-plan dans les Réglages : la lecture continue quand vous changez d'app ou verrouillez l'écran, avec titre, pochette et commandes sur l'écran verrouillé et dans le centre de contrôle. La vidéo peut flotter au-dessus des autres apps avec Picture in Picture."),
        ("L'app collecte-t-elle des données ?",
         "Non. Offgrid Media n'a ni compte, ni serveur, ni analyse, ni SDK tiers. Son manifeste de confidentialité App Store déclare aucun suivi et aucune donnée collectée. La seule autorisation demandée concerne les notifications."),
        ("Combien coûte Offgrid Media ?",
         "Rien. Pas d'abonnement, pas d'achats intégrés, pas de publicité."),
    ],
    "close_h2": "Votre médiathèque. Votre appareil. Sans réseau.",
    "close_p": "Offgrid Media est gratuite, pour iPhone et iPad, en 11 langues.",
    "close_meta": "Aucun compte · Aucune pub · Aucun suivi",
    "stat_langs": "Langues", "stat_zero": "Comptes, pubs, traceurs",
    "stat_device": "Sur l'appareil", "stat_ios": "iOS, iPhone et iPad",
    "privacy_title": "Politique de confidentialité – Offgrid Media",
    "privacy_desc": "Offgrid Media ne collecte aucune donnée personnelle. Aucun compte, aucune analyse, aucun SDK tiers, aucune synchronisation cloud.",
    "privacy_h1": "Politique de confidentialité",
    "privacy_updated": "Dernière mise à jour le 1er août 2026",
    "privacy_back": "Retour à Offgrid Media",
    "policy": [
        ("p", "<strong>Offgrid Media ne collecte, ne stocke et ne transmet aucune donnée personnelle.</strong> Il n'y a ni compte, ni service dorsal, ni analyse. Votre médiathèque est un ensemble de fichiers sur votre appareil, et elle y reste."),
        ("h2", "Ce que l'app collecte"),
        ("p", "Rien. Le manifeste de confidentialité App Store de l'app déclare aucun suivi et aucune donnée collectée. Il n'y a aucun identifiant publicitaire, aucun service de rapport de plantage et aucun SDK d'analyse ou de marketing tiers dans l'app."),
        ("h2", "Où vivent vos médias"),
        ("ul", ["Tout ce que vous importez est écrit dans un dossier sur votre appareil. Vous choisissez lequel dans les Réglages.",
                "L'app prend en charge l'app Fichiers : vous pouvez consulter et gérer vous-même ces fichiers.",
                "Il n'y a aucune synchronisation cloud ni téléversement. Si vous choisissez un dossier synchronisé par iCloud Drive, cette synchronisation est assurée par Apple selon vos propres réglages iCloud, pas par l'app."]),
        ("h2", "Quand l'app utilise le réseau"),
        ("ul", ["<strong>La lecture n'utilise jamais le réseau.</strong> Les fichiers sont lus depuis le stockage local.",
                "<strong>L'ajout via un lien, si.</strong> Si vous collez ou partagez un lien, l'app contacte cette adresse et le serveur de médias correspondant, en HTTPS, pour récupérer le fichier. Rien de cette requête n'est envoyé au développeur.",
                "<strong>Les liens des Réglages</strong> s'ouvrent normalement dans votre navigateur."]),
        ("h2", "Autorisations"),
        ("p", "L'app demande une seule autorisation : les notifications, pour vous indiquer qu'un import est terminé ou a échoué. Vous pouvez la refuser, l'app fonctionne quand même. L'import depuis Photos utilise le sélecteur de photos standard d'iOS, qui s'exécute hors de l'app et ne nécessite aucun accès à la photothèque."),
        ("h2", "Diagnostics"),
        ("p", "Les Réglages contiennent un journal d'activité local pour voir ce que l'app a fait. Il ne quitte jamais votre appareil et les entrées sont supprimées automatiquement au bout de deux jours."),
        ("h2", "Enfants"),
        ("p", "L'app est classée 4+ et ne collecte aucune donnée de qui que ce soit, y compris des enfants."),
        ("h2", "Ce site web"),
        ("p", 'Indépendamment de l\'app : lorenzmaierhofer.com utilise <a href="https://plausible.io/privacy-focused-web-analytics" target="_blank" rel="noopener">Plausible Analytics</a> pour des statistiques de pages agrégées. Plausible ne dépose aucun cookie et ne collecte aucune donnée personnelle. Cela concerne uniquement le site — l\'app elle-même ne contient aucune analyse.'),
        ("h2", "Le contenu que vous ajoutez"),
        ("p", "N'ajoutez que du contenu que vous avez le droit de conserver. Le respect des conditions d'utilisation de chaque plateforme et des lois applicables relève de votre seule responsabilité."),
        ("h2", "Modifications"),
        ("p", "Si cette politique change, la version mise à jour sera publiée sur cette page avec une nouvelle date."),
        ("h2", "Contact"),
        ("p", 'Questions sur la confidentialité : <a href="mailto:awr9a2npb@mozmail.com">awr9a2npb@mozmail.com</a>'),
    ],
},

"es": {
    "feature_heads": [
        "Importa desde Archivos y Fotos",
        "Organízalo a tu manera",
        "Pensado para el modo sin conexión",
        "Un reproductor de verdad",
        "Audio en segundo plano",
        "Elige tu calidad",
        "Sin cuenta. Sin anuncios. Sin rastreo.",
    ],
    "meta_title": "Offgrid Media – Tu biblioteca multimedia sin conexión para iPhone y iPad",
    "meta_desc": "Offgrid Media es una biblioteca multimedia privada para iPhone y iPad. Importa vídeo y audio desde Archivos o Fotos, organízalo en carpetas y reprodúcelo todo sin conexión. Sin cuenta, sin anuncios, sin rastreo.",
    "og_title": "Offgrid Media – Tu biblioteca multimedia sin conexión",
    "og_desc": "Importa vídeo y audio desde Archivos o Fotos, organízalo en carpetas y reprodúcelo todo sin conexión. En el dispositivo. Sin cuenta.",
    "og_image_alt": "Offgrid Media – Todo lo que guardas, sin conexión",
    "currency": "EUR",
    "nav_library": "La biblioteca", "nav_features": "Funciones", "nav_privacy": "Privacidad",
    "nav_faq": "Preguntas", "nav_overview": "Resumen",
    "nav_toggle": "Mostrar navegación", "theme_toggle": "Cambiar tema",
    "footer_nav": "Pie de página", "device": "Dispositivo",
    "h1": "Todo lo que guardas,|sin conexión.",
    "cta_soon": "Muy pronto en el App Store", "cta_meta": "Gratis · iPhone y iPad",
    "cta_meta2": "Gratis · iOS 16.1+", "cta_secondary": "Ver cómo funciona",
    "cta_live": "Descargar en el App Store",
    "switch_off": "Modo avión activado", "switch_on": "Modo avión desactivado",
    "hint_off": "Pruébalo. La red está apagada y tu biblioteca sigue sonando.",
    "hint_on": "Red de vuelta. Nada cambia en tu biblioteca.",
    "chip_network": "Red", "chip_no_conn": "Sin conexión", "chip_conn": "Conectado",
    "chip_library": "Tu biblioteca", "chip_playing": "Reproduciendo",
    "chip_caption": "Igual en ambos casos. De eso se trata.",
    "video_label": "Vista previa de Offgrid Media: importar, organizar y reproducir sin conexión",
    "lbl_library": "La biblioteca",
    "h2_library": "Un único lugar ordenado para tus propios archivos",
    "sub_library": "Carpetas, búsqueda y un filtro por vídeo o audio. Las miniaturas salen del propio archivo y se conservan la carátula y los metadatos.",
    "lbl_how": "Cómo funciona", "h2_how": "Importa, organiza, reproduce",
    "lbl_features": "Qué hace",
    "h2_features": "Un reproductor de verdad, no una carpeta de archivos",
    "sub_features": "Todo lo de abajo funciona con la red apagada.",
    "h2_privacy": "Nada que recopilar, porque no hay adónde enviarlo",
    "sub_privacy": "Offgrid Media no tiene cuenta ni servidor propio. Su manifiesto de privacidad del App Store declara cero rastreo y cero datos recopilados.",
    "privacy_items": [
        ("Sin cuenta", "Sin registro, sin inicio de sesión, sin perfil. Abres la app y funciona."),
        ("Sin analítica en la app", "Sin SDK de rastreo, sin informes de fallos, sin frameworks de publicidad."),
        ("Sin sincronización en la nube", "Tu biblioteca no se sube a ningún sitio. No hay sincronización con iCloud ni servicio de copia de seguridad."),
        ("Un solo permiso", "Notificaciones, para avisarte cuando termina una importación. Es el único que pide."),
    ],
    "privacy_link": "Leer la política de privacidad completa",
    "lbl_faq": "Preguntas", "h2_faq": "Preguntas frecuentes",
    "faq": [
        ("¿Offgrid Media necesita conexión a internet?",
         "No. Una vez que algo está en tu biblioteca vive en tu dispositivo y se reproduce con la red apagada. Al reproducir no se transmite nada, así que no hay cargas ni conexión que perder."),
        ("¿Dónde se guardan mis archivos?",
         "En una carpeta de tu dispositivo, dentro del almacenamiento de la app. Puedes elegir otra carpeta en Ajustes y, como la app es compatible con la app Archivos, puedes ver ahí los mismos archivos. No se sube nada y no hay sincronización en la nube."),
        ("¿Cómo añado archivos a la biblioteca?",
         "Importando desde Archivos (iCloud Drive o el dispositivo), desde tu fototeca, o añadiendo desde un enlace que tengas derecho a conservar. La importación es la vía principal; el enlace es una comodidad secundaria."),
        ("¿Sigue sonando el audio en segundo plano?",
         "Sí. Activa el audio en segundo plano en Ajustes y la reproducción continúa al cambiar de app o bloquear la pantalla, con título, carátula y controles en la pantalla bloqueada y en el centro de control. El vídeo puede flotar sobre otras apps con imagen dentro de imagen."),
        ("¿La app recopila datos?",
         "No. Offgrid Media no tiene cuenta, ni servidor, ni analítica, ni SDK de terceros. Su manifiesto de privacidad del App Store declara cero rastreo y cero datos recopilados. El único permiso que pide son las notificaciones."),
        ("¿Cuánto cuesta Offgrid Media?",
         "Nada. Sin suscripción, sin compras dentro de la app, sin anuncios."),
    ],
    "close_h2": "Tu biblioteca. Tu dispositivo. Sin cobertura.",
    "close_p": "Offgrid Media es gratis, para iPhone y iPad, en 11 idiomas.",
    "close_meta": "Sin cuenta · Sin anuncios · Sin rastreo",
    "stat_langs": "Idiomas", "stat_zero": "Cuentas, anuncios, rastreadores",
    "stat_device": "En el dispositivo", "stat_ios": "iOS, iPhone y iPad",
    "privacy_title": "Política de privacidad – Offgrid Media",
    "privacy_desc": "Offgrid Media no recopila datos personales. Sin cuenta, sin analítica, sin SDK de terceros y sin sincronización en la nube.",
    "privacy_h1": "Política de privacidad",
    "privacy_updated": "Última actualización: 1 de agosto de 2026",
    "privacy_back": "Volver a Offgrid Media",
    "policy": [
        ("p", "<strong>Offgrid Media no recopila, almacena ni transmite ningún dato personal.</strong> No hay cuenta, ni servicio en servidor, ni analítica. Tu biblioteca es un conjunto de archivos en tu dispositivo, y ahí se queda."),
        ("h2", "Qué recopila la app"),
        ("p", "Nada. El manifiesto de privacidad del App Store de la app declara cero rastreo y cero tipos de datos recopilados. No hay identificadores publicitarios, ni servicios de informes de fallos, ni SDK de analítica o marketing de terceros."),
        ("h2", "Dónde viven tus archivos"),
        ("ul", ["Todo lo que importas se escribe en una carpeta de tu dispositivo. Tú eliges cuál en Ajustes.",
                "La app es compatible con la app Archivos, así que puedes ver y gestionar esos mismos archivos tú mismo.",
                "No hay sincronización en la nube ni subida de ningún tipo. Si eliges una carpeta que iCloud Drive sincroniza, esa sincronización la hace Apple según tus propios ajustes de iCloud, no la app."]),
        ("h2", "Cuándo usa la red la app"),
        ("ul", ["<strong>La reproducción nunca usa la red.</strong> Los archivos se reproducen desde el almacenamiento local.",
                "<strong>Añadir desde un enlace, sí.</strong> Si pegas o compartes un enlace, la app contacta con esa dirección y con el servidor de medios al que apunta, por HTTPS, para descargar el archivo. Nada de esa petición se envía al desarrollador.",
                "<strong>Los enlaces de Ajustes</strong> se abren en tu navegador con normalidad."]),
        ("h2", "Permisos"),
        ("p", "La app pide un permiso: notificaciones, para avisarte de que una importación terminó o falló. Puedes rechazarlo y la app sigue funcionando. Importar desde Fotos usa el selector de fotos estándar de iOS, que se ejecuta fuera de la app y no requiere acceso a la fototeca."),
        ("h2", "Diagnóstico"),
        ("p", "Ajustes incluye un registro de actividad local para que veas qué ha hecho la app. Nunca sale de tu dispositivo y las entradas se borran automáticamente a los dos días."),
        ("h2", "Menores"),
        ("p", "La app tiene clasificación 4+ y no recopila datos de nadie, tampoco de menores."),
        ("h2", "Este sitio web"),
        ("p", 'Aparte de la app: lorenzmaierhofer.com usa <a href="https://plausible.io/privacy-focused-web-analytics" target="_blank" rel="noopener">Plausible Analytics</a> para estadísticas agregadas de páginas vistas. Plausible no usa cookies ni recopila datos personales. Esto se aplica solo al sitio web; la app no contiene analítica alguna.'),
        ("h2", "El contenido que añades"),
        ("p", "Añade solo contenido que tengas derecho a conservar. El cumplimiento de las condiciones de servicio de cada plataforma y de las leyes aplicables es responsabilidad exclusivamente tuya."),
        ("h2", "Cambios"),
        ("p", "Si esta política cambia, la versión actualizada se publicará en esta página con una fecha nueva."),
        ("h2", "Contacto"),
        ("p", 'Dudas sobre privacidad: <a href="mailto:awr9a2npb@mozmail.com">awr9a2npb@mozmail.com</a>'),
    ],
},

"pt": {
    "feature_heads": [
        "Importe de Arquivos e Fotos",
        "Organize do seu jeito",
        "Feito para o offline",
        "Um player de verdade",
        "Áudio em segundo plano",
        "Escolha a qualidade",
        "Sem conta. Sem anúncios. Sem rastreamento.",
    ],
    "meta_title": "Offgrid Media – Sua biblioteca de mídia offline para iPhone e iPad",
    "meta_desc": "O Offgrid Media é uma biblioteca de mídia privada para iPhone e iPad. Importe vídeo e áudio de Arquivos ou Fotos, organize em pastas e reproduza tudo offline. Sem conta, sem anúncios, sem rastreamento.",
    "og_title": "Offgrid Media – Sua biblioteca de mídia offline",
    "og_desc": "Importe vídeo e áudio de Arquivos ou Fotos, organize em pastas e reproduza tudo offline. No dispositivo. Sem conta.",
    "og_image_alt": "Offgrid Media – Tudo o que você guarda, offline",
    "currency": "BRL",
    "nav_library": "A biblioteca", "nav_features": "Recursos", "nav_privacy": "Privacidade",
    "nav_faq": "Perguntas", "nav_overview": "Visão geral",
    "nav_toggle": "Abrir navegação", "theme_toggle": "Alternar tema",
    "footer_nav": "Rodapé", "device": "Dispositivo",
    "h1": "Tudo o que você guarda,|offline.",
    "cta_soon": "Em breve na App Store", "cta_meta": "Grátis · iPhone e iPad",
    "cta_meta2": "Grátis · iOS 16.1+", "cta_secondary": "Veja como funciona",
    "cta_live": "Baixar na App Store",
    "switch_off": "Modo avião ligado", "switch_on": "Modo avião desligado",
    "hint_off": "Experimente. A rede está desligada — sua biblioteca continua tocando.",
    "hint_on": "Rede de volta. Nada muda na sua biblioteca.",
    "chip_network": "Rede", "chip_no_conn": "Sem conexão", "chip_conn": "Conectado",
    "chip_library": "Sua biblioteca", "chip_playing": "Reproduzindo",
    "chip_caption": "Igual nos dois casos. É esse o ponto.",
    "video_label": "Prévia do Offgrid Media: importar, organizar e reproduzir offline",
    "lbl_library": "A biblioteca",
    "h2_library": "Um lugar organizado para as mídias que são suas",
    "sub_library": "Pastas, busca e filtro por vídeo ou áudio. As miniaturas vêm do próprio arquivo, e a capa e os metadados são preservados.",
    "lbl_how": "Como funciona", "h2_how": "Importe, organize, reproduza",
    "lbl_features": "O que ele faz",
    "h2_features": "Um player de verdade, não uma pasta de arquivos",
    "sub_features": "Tudo abaixo funciona com a rede desligada.",
    "h2_privacy": "Nada a coletar, porque não há para onde enviar",
    "sub_privacy": "O Offgrid Media não tem conta nem servidor próprio. O manifesto de privacidade da App Store declara nenhum rastreamento e nenhum dado coletado.",
    "privacy_items": [
        ("Sem conta", "Sem cadastro, sem login, sem perfil. Abriu o app, funciona."),
        ("Sem análise no app", "Sem SDKs de rastreamento, sem relatórios de falhas, sem frameworks de anúncios."),
        ("Sem sincronização na nuvem", "Sua biblioteca não é enviada para lugar nenhum. Não há sincronização com o iCloud nem serviço de backup."),
        ("Uma permissão", "Notificações, para avisar quando uma importação termina. É a única que ele pede."),
    ],
    "privacy_link": "Ler a política de privacidade completa",
    "lbl_faq": "Perguntas", "h2_faq": "Perguntas frequentes",
    "faq": [
        ("O Offgrid Media precisa de internet?",
         "Não. Depois que algo está na sua biblioteca, fica no seu dispositivo e toca com a rede desligada. Nada é transmitido durante a reprodução, então não há buffer nem conexão para cair."),
        ("Onde meus arquivos ficam guardados?",
         "Em uma pasta no seu dispositivo, dentro do armazenamento do app. Você pode escolher outra pasta nos Ajustes e, como o app funciona com o app Arquivos, dá para ver os mesmos arquivos por lá. Nada é enviado e não há sincronização na nuvem."),
        ("Como coloco mídias na biblioteca?",
         "Importando de Arquivos (iCloud Drive ou do aparelho), da sua fototeca, ou adicionando por um link que você tem o direito de guardar. A importação é o caminho principal; o link é uma conveniência secundária."),
        ("O áudio continua em segundo plano?",
         "Sim. Ative o áudio em segundo plano nos Ajustes e a reprodução segue quando você troca de app ou bloqueia a tela, com título, capa e controles na tela bloqueada e na Central de Controle. O vídeo pode flutuar sobre outros apps com Picture in Picture."),
        ("O app coleta algum dado?",
         "Não. O Offgrid Media não tem conta, servidor, análise nem SDKs de terceiros. O manifesto de privacidade da App Store declara nenhum rastreamento e nenhum dado coletado. A única permissão pedida é a de notificações."),
        ("Quanto custa o Offgrid Media?",
         "Nada. Sem assinatura, sem compras no app, sem anúncios."),
    ],
    "close_h2": "Sua biblioteca. Seu dispositivo. Sem precisar de sinal.",
    "close_p": "O Offgrid Media é grátis, para iPhone e iPad, em 11 idiomas.",
    "close_meta": "Sem conta · Sem anúncios · Sem rastreamento",
    "stat_langs": "Idiomas", "stat_zero": "Contas, anúncios, rastreadores",
    "stat_device": "No dispositivo", "stat_ios": "iOS, iPhone e iPad",
    "privacy_title": "Política de Privacidade – Offgrid Media",
    "privacy_desc": "O Offgrid Media não coleta dados pessoais. Sem conta, sem análise, sem SDKs de terceiros e sem sincronização na nuvem.",
    "privacy_h1": "Política de privacidade",
    "privacy_updated": "Última atualização: 1 de agosto de 2026",
    "privacy_back": "Voltar ao Offgrid Media",
    "policy": [
        ("p", "<strong>O Offgrid Media não coleta, armazena nem transmite dados pessoais.</strong> Não há conta, serviço de servidor nem análise. Sua biblioteca é um conjunto de arquivos no seu dispositivo, e é lá que ela fica."),
        ("h2", "O que o app coleta"),
        ("p", "Nada. O manifesto de privacidade da App Store declara nenhum rastreamento e nenhum tipo de dado coletado. Não há identificadores de publicidade, serviços de relatório de falhas nem SDKs de análise ou marketing de terceiros no app."),
        ("h2", "Onde ficam suas mídias"),
        ("ul", ["Tudo o que você importa é gravado em uma pasta no seu dispositivo. Você escolhe qual nos Ajustes.",
                "O app funciona com o app Arquivos, então você mesmo pode ver e gerenciar esses arquivos.",
                "Não há sincronização na nuvem nem envio de qualquer tipo. Se você escolher uma pasta que o iCloud Drive sincroniza, essa sincronização é feita pela Apple conforme os seus ajustes do iCloud, não pelo app."]),
        ("h2", "Quando o app usa a rede"),
        ("ul", ["<strong>A reprodução nunca usa a rede.</strong> Os arquivos tocam a partir do armazenamento local.",
                "<strong>Adicionar por link, sim.</strong> Se você colar ou compartilhar um link, o app acessa esse endereço e o servidor de mídia correspondente, por HTTPS, para baixar o arquivo. Nada dessa requisição é enviado ao desenvolvedor.",
                "<strong>Os links nos Ajustes</strong> abrem no seu navegador normalmente."]),
        ("h2", "Permissões"),
        ("p", "O app pede uma permissão: notificações, para avisar que uma importação terminou ou falhou. Você pode recusar e o app continua funcionando. Importar de Fotos usa o seletor de fotos padrão do iOS, que roda fora do app e não exige acesso à fototeca."),
        ("h2", "Diagnóstico"),
        ("p", "Os Ajustes têm um registro de atividade local para você ver o que o app fez. Ele nunca sai do seu dispositivo e as entradas são apagadas automaticamente após dois dias."),
        ("h2", "Crianças"),
        ("p", "O app é classificado como 4+ e não coleta dados de ninguém, inclusive de crianças."),
        ("h2", "Este site"),
        ("p", 'Separado do app: lorenzmaierhofer.com usa o <a href="https://plausible.io/privacy-focused-web-analytics" target="_blank" rel="noopener">Plausible Analytics</a> para estatísticas agregadas de visualizações. O Plausible não usa cookies nem coleta dados pessoais. Isso vale apenas para o site — o app em si não contém análise nenhuma.'),
        ("h2", "O conteúdo que você adiciona"),
        ("p", "Adicione apenas conteúdo que você tem o direito de guardar. O cumprimento dos termos de serviço de qualquer plataforma e das leis aplicáveis é de sua exclusiva responsabilidade."),
        ("h2", "Alterações"),
        ("p", "Se esta política mudar, a versão atualizada será publicada nesta página com uma nova data."),
        ("h2", "Contato"),
        ("p", 'Dúvidas sobre privacidade: <a href="mailto:awr9a2npb@mozmail.com">awr9a2npb@mozmail.com</a>'),
    ],
},

}

STRINGS.update(STRINGS_B)
