# -*- coding: utf-8 -*-
"""UI strings, part two: id, ru, hi, ar, zh."""

STRINGS_B = {

"id": {
    "feature_heads": [
        "Impor dari Files dan Foto",
        "Atur sesuka Anda",
        "Dibuat untuk offline",
        "Pemutar sungguhan",
        "Audio latar",
        "Pilih kualitas Anda",
        "Bab",
        "Folder utuh, sekali jalan",
        "Hanya yang Anda pakai",
        "Tanpa akun. Tanpa iklan. Tanpa pelacakan.",
    ],
    "meta_title": "Offgrid Media – Pustaka Media Offline Pribadi untuk iPhone & iPad",
    "meta_desc": "Offgrid Media adalah pustaka media pribadi untuk iPhone dan iPad. Impor video dan audio dari Files atau Foto, atur dalam folder, dan putar semuanya secara offline. Tanpa akun, tanpa iklan, tanpa pelacakan.",
    "og_title": "Offgrid Media – Pustaka Media Offline Pribadi Anda",
    "og_desc": "Impor video dan audio dari Files atau Foto, atur dalam folder, dan putar semuanya offline. Di perangkat. Tanpa akun.",
    "og_image_alt": "Offgrid Media – Semua yang Anda simpan, offline",
    "currency": "USD",
    "nav_library": "Pustaka", "nav_features": "Fitur", "nav_privacy": "Privasi",
    "nav_faq": "Tanya jawab", "nav_overview": "Ringkasan",
    "nav_toggle": "Buka navigasi", "theme_toggle": "Ganti tema",
    "footer_nav": "Footer", "device": "Perangkat",
    "h1": "Semua yang Anda simpan,|offline.",
    "cta_soon": "Segera di App Store", "cta_meta": "Gratis · iPhone & iPad",
    "cta_meta2": "Gratis · iOS 16.1+", "cta_secondary": "Lihat cara kerjanya",
    "cta_live": "Unduh di App Store",
    "switch_off": "Mode pesawat aktif", "switch_on": "Mode pesawat nonaktif",
    "hint_off": "Coba saja. Jaringan mati — pustaka Anda tetap berjalan.",
    "hint_on": "Jaringan kembali. Tidak ada yang berubah di pustaka Anda.",
    "chip_network": "Jaringan", "chip_no_conn": "Tidak ada koneksi", "chip_conn": "Terhubung",
    "chip_library": "Pustaka Anda", "chip_playing": "Memutar",
    "chip_caption": "Sama di kedua keadaan. Itulah intinya.",
    "video_label": "Pratinjau Offgrid Media: mengimpor, mengatur, dan memutar secara offline",
    "lbl_library": "Pustaka",
    "h2_library": "Satu tempat rapi untuk media milik Anda sendiri",
    "sub_library": "Folder, pencarian, dan saringan video atau audio. Gambar mini diambil dari berkasnya sendiri, sampul album dan metadata tetap terjaga.",
    "lbl_how": "Cara kerjanya", "h2_how": "Impor, atur, putar",
    "lbl_features": "Apa yang bisa dilakukan",
    "h2_features": "Pemutar sungguhan, bukan sekadar folder berkas",
    "sub_features": "Semua di bawah ini berfungsi tanpa jaringan.",
    "h2_privacy": "Tidak ada yang dikumpulkan, karena tidak ada tujuan pengiriman",
    "sub_privacy": "Offgrid Media tidak punya akun maupun server sendiri. Manifes privasi App Store-nya menyatakan tanpa pelacakan dan tanpa data yang dikumpulkan.",
    "privacy_items": [
        ("Tanpa akun", "Tanpa pendaftaran, tanpa masuk, tanpa profil. Buka aplikasinya, langsung jalan."),
        ("Tanpa analitik di aplikasi", "Tanpa SDK pelacakan, tanpa pelapor kerusakan, tanpa kerangka kerja iklan."),
        ("Tanpa sinkronisasi awan", "Pustaka Anda tidak diunggah ke mana pun. Tidak ada sinkronisasi iCloud dan tidak ada layanan cadangan."),
        ("Satu izin", "Notifikasi, agar aplikasi bisa memberi tahu saat impor selesai. Hanya itu yang diminta."),
    ],
    "privacy_link": "Baca kebijakan privasi lengkap",
    "lbl_faq": "Pertanyaan", "h2_faq": "Pertanyaan umum",
    "faq": [
        ("Apakah Offgrid Media perlu koneksi internet?",
         "Tidak. Begitu ada di pustaka, item tersimpan di perangkat Anda dan bisa diputar tanpa jaringan. Tidak ada yang dialirkan saat pemutaran, jadi tidak ada buffering dan tidak ada koneksi yang bisa putus."),
        ("Di mana berkas saya disimpan?",
         "Di sebuah folder pada perangkat Anda, di dalam penyimpanan aplikasi. Anda bisa memilih folder pustaka lain di Pengaturan, dan karena aplikasi mendukung app Files, berkas yang sama bisa Anda telusuri di sana. Tidak ada yang diunggah dan tidak ada sinkronisasi awan."),
        ("Bagaimana cara memasukkan media ke pustaka?",
         "Impor dari Files (iCloud Drive atau perangkat), impor dari pustaka foto, atau tambahkan dari tautan yang berhak Anda simpan — tempel tautannya di aplikasi, atau gunakan menu Bagikan di peramban Anda lalu pilih Offgrid Media. Impor adalah jalur utama; menambahkan dari tautan hanya kemudahan tambahan."),
        ("Apakah audio tetap berjalan di latar belakang?",
         "Ya. Aktifkan audio latar di Pengaturan, maka pemutaran berlanjut saat Anda berpindah aplikasi atau mengunci layar, lengkap dengan judul, sampul, dan kontrol di Layar Terkunci serta Pusat Kontrol. Video bisa mengambang di atas aplikasi lain dengan Picture in Picture. Video juga bisa diputar layar penuh, dan di iPad aplikasi tetap berjalan berdampingan dengan aplikasi lain lewat Split View."),
        ("Apakah aplikasi mengumpulkan data?",
         "Tidak. Offgrid Media tidak punya akun, server, analitik, maupun SDK pihak ketiga. Manifes privasi App Store-nya menyatakan tanpa pelacakan dan tanpa data yang dikumpulkan. Satu-satunya izin yang diminta adalah notifikasi."),
        ("Berapa harga Offgrid Media?",
         "Gratis. Tanpa langganan, tanpa pembelian dalam aplikasi, tanpa iklan."),
    ],
    "close_h2": "Pustaka Anda. Perangkat Anda. Tanpa perlu sinyal.",
    "close_p": "Offgrid Media gratis, untuk iPhone dan iPad, dalam 11 bahasa.",
    "close_meta": "Tanpa akun · Tanpa iklan · Tanpa pelacakan",
    "stat_langs": "Bahasa", "stat_zero": "Akun, iklan, pelacak",
    "stat_device": "Di perangkat", "stat_ios": "iOS, iPhone & iPad",
    "privacy_title": "Kebijakan Privasi – Offgrid Media",
    "privacy_desc": "Offgrid Media tidak mengumpulkan data pribadi. Tanpa akun, tanpa analitik, tanpa SDK pihak ketiga, tanpa sinkronisasi awan.",
    "privacy_h1": "Kebijakan privasi",
    "privacy_updated": "Terakhir diperbarui 1 Agustus 2026",
    "privacy_back": "Kembali ke Offgrid Media",
    "policy": [
        ("p", "<strong>Offgrid Media tidak mengumpulkan, menyimpan, atau mengirimkan data pribadi apa pun.</strong> Tidak ada akun, tidak ada layanan server, tidak ada analitik. Pustaka Anda adalah sekumpulan berkas di perangkat Anda, dan tetap di sana."),
        ("h2", "Apa yang dikumpulkan aplikasi"),
        ("p", "Tidak ada. Manifes privasi App Store aplikasi ini menyatakan tanpa pelacakan dan tanpa jenis data yang dikumpulkan. Tidak ada pengenal iklan, layanan pelaporan kerusakan, atau SDK analitik maupun pemasaran pihak ketiga di dalamnya."),
        ("h2", "Di mana media Anda berada"),
        ("ul", ["Semua yang Anda impor ditulis ke sebuah folder di perangkat Anda. Anda memilih foldernya di Pengaturan.",
                "Aplikasi mendukung app Files, jadi Anda bisa menelusuri dan mengelola berkas yang sama sendiri.",
                "Tidak ada sinkronisasi awan dan tidak ada pengunggahan apa pun. Jika Anda memilih folder yang disinkronkan iCloud Drive, sinkronisasi itu dilakukan Apple sesuai pengaturan iCloud Anda, bukan oleh aplikasi."]),
        ("h2", "Kapan aplikasi memakai jaringan"),
        ("ul", ["<strong>Pemutaran tidak pernah memakai jaringan.</strong> Berkas diputar dari penyimpanan lokal.",
                "<strong>Menambahkan dari tautan memakai jaringan.</strong> Jika Anda menempel atau membagikan tautan, aplikasi menghubungi alamat itu dan server media yang dituju lewat HTTPS untuk mengambil berkasnya. Tidak ada bagian dari permintaan itu yang dikirim ke pengembang.",
                "<strong>Tautan yang Anda ketuk di Pengaturan</strong> terbuka di peramban seperti biasa."]),
        ("h2", "Izin"),
        ("p", "Aplikasi meminta satu izin: notifikasi, agar bisa memberi tahu saat impor selesai atau gagal. Anda boleh menolaknya dan aplikasi tetap berfungsi. Impor dari Foto memakai pemilih foto standar iOS, yang berjalan di luar aplikasi dan tidak memerlukan akses ke pustaka foto."),
        ("h2", "Diagnostik"),
        ("p", "Pengaturan memuat log aktivitas lokal agar Anda bisa melihat apa yang dilakukan aplikasi. Log itu tidak pernah meninggalkan perangkat Anda dan entrinya terhapus otomatis setelah dua hari."),
        ("h2", "Anak-anak"),
        ("p", "Aplikasi ini berperingkat 4+ dan tidak mengumpulkan data dari siapa pun, termasuk anak-anak."),
        ("h2", "Situs web ini"),
        ("p", 'Terpisah dari aplikasi: lorenzmaierhofer.com memakai <a href="https://plausible.io/privacy-focused-web-analytics" target="_blank" rel="noopener">Plausible Analytics</a> untuk statistik tampilan halaman secara agregat. Plausible tidak memasang cookie dan tidak mengumpulkan data pribadi. Ini hanya berlaku untuk situs web — aplikasinya sendiri tidak memuat analitik apa pun.'),
        ("h2", "Konten yang Anda tambahkan"),
        ("p", "Harap hanya tambahkan konten yang berhak Anda simpan. Kepatuhan terhadap ketentuan layanan platform mana pun dan hukum yang berlaku sepenuhnya menjadi tanggung jawab Anda."),
        ("h2", "Perubahan"),
        ("p", "Jika kebijakan ini berubah, versi terbaru akan diterbitkan di halaman ini dengan tanggal baru."),
        ("h2", "Kontak"),
        ("p", 'Pertanyaan soal privasi: <a href="mailto:awr9a2npb@mozmail.com">awr9a2npb@mozmail.com</a>'),
    ],
},

"ru": {
    "feature_heads": [
        "Импорт из Файлов и Фото",
        "Порядок по-вашему",
        "Создано для офлайна",
        "Настоящий плеер",
        "Фоновое аудио",
        "Выберите качество",
        "Главы",
        "Целые папки сразу",
        "Только то, что нужно",
        "Без аккаунта. Без рекламы. Без слежки.",
    ],
    "meta_title": "Offgrid Media — личная офлайн-медиатека для iPhone и iPad",
    "meta_desc": "Offgrid Media — личная медиатека для iPhone и iPad. Импортируйте видео и аудио из Файлов или Фото, раскладывайте по папкам и слушайте и смотрите всё офлайн. Без аккаунта, без рекламы, без слежки.",
    "og_title": "Offgrid Media — ваша личная офлайн-медиатека",
    "og_desc": "Импортируйте видео и аудио из Файлов или Фото, раскладывайте по папкам и воспроизводите всё офлайн. На устройстве. Без аккаунта.",
    "og_image_alt": "Offgrid Media — всё, что вы храните, офлайн",
    "currency": "RUB",
    "nav_library": "Медиатека", "nav_features": "Возможности", "nav_privacy": "Конфиденциальность",
    "nav_faq": "Вопросы", "nav_overview": "Обзор",
    "nav_toggle": "Открыть меню", "theme_toggle": "Сменить тему",
    "footer_nav": "Подвал", "device": "Устройство",
    "h1": "Всё, что вы храните,|офлайн.",
    "cta_soon": "Скоро в App Store", "cta_meta": "Бесплатно · iPhone и iPad",
    "cta_meta2": "Бесплатно · iOS 16.1+", "cta_secondary": "Как это работает",
    "cta_live": "Загрузить в App Store",
    "switch_off": "Авиарежим включён", "switch_on": "Авиарежим выключен",
    "hint_off": "Попробуйте. Сети нет — медиатека всё равно играет.",
    "hint_on": "Сеть вернулась. Для вашей медиатеки ничего не изменилось.",
    "chip_network": "Сеть", "chip_no_conn": "Нет соединения", "chip_conn": "Подключено",
    "chip_library": "Ваша медиатека", "chip_playing": "Воспроизводится",
    "chip_caption": "Одинаково в обоих случаях. В этом весь смысл.",
    "video_label": "Обзор Offgrid Media: импорт, порядок и воспроизведение офлайн",
    "lbl_library": "Медиатека",
    "h2_library": "Одно аккуратное место для ваших собственных медиафайлов",
    "sub_library": "Папки, поиск и фильтр по видео или аудио. Миниатюры берутся из самого файла, обложки и метаданные сохраняются.",
    "lbl_how": "Как это работает", "h2_how": "Импорт, порядок, воспроизведение",
    "lbl_features": "Что она умеет",
    "h2_features": "Настоящий плеер, а не папка с файлами",
    "sub_features": "Всё, что ниже, работает без сети.",
    "h2_privacy": "Нечего собирать, потому что некуда отправлять",
    "sub_privacy": "У Offgrid Media нет аккаунта и нет собственного сервера. Манифест конфиденциальности в App Store заявляет: никакого отслеживания и никаких собираемых данных.",
    "privacy_items": [
        ("Без аккаунта", "Без регистрации, без входа, без профиля. Открыли приложение — и всё работает."),
        ("Без аналитики в приложении", "Никаких SDK отслеживания, отчётов о сбоях и рекламных фреймворков."),
        ("Без облачной синхронизации", "Ваша медиатека никуда не выгружается. Нет синхронизации с iCloud и нет службы резервного копирования."),
        ("Одно разрешение", "Уведомления, чтобы приложение сообщило, когда импорт завершён. Больше оно ничего не запрашивает."),
    ],
    "privacy_link": "Читать полную политику конфиденциальности",
    "lbl_faq": "Вопросы", "h2_faq": "Частые вопросы",
    "faq": [
        ("Нужен ли Offgrid Media интернет?",
         "Нет. Всё, что попало в медиатеку, лежит на вашем устройстве и воспроизводится без сети. При воспроизведении ничего не транслируется, поэтому нет ни буферизации, ни соединения, которое может оборваться."),
        ("Где хранятся мои файлы?",
         "В папке на вашем устройстве, внутри хранилища приложения. В настройках можно выбрать другую папку медиатеки, а поскольку приложение поддерживает приложение «Файлы», те же файлы видны и там. Ничего не выгружается, облачной синхронизации нет."),
        ("Как добавить медиафайлы в медиатеку?",
         "Импорт из «Файлов» (iCloud Drive или устройство), импорт из медиатеки «Фото» или добавление по ссылке, которую вы вправе хранить: вставьте её в приложение или нажмите «Поделиться» в браузере и выберите Offgrid Media. Импорт — основной путь; ссылка — второстепенное удобство."),
        ("Продолжается ли воспроизведение аудио в фоне?",
         "Да. Включите фоновое аудио в настройках — воспроизведение продолжится при переключении приложений и блокировке экрана, с названием, обложкой и управлением на экране блокировки и в пункте управления. Видео можно вывести поверх других приложений в режиме «Картинка в картинке». Видео также воспроизводится в полноэкранном режиме, а на iPad приложение продолжает работать рядом с другим в Split View."),
        ("Собирает ли приложение данные?",
         "Нет. У Offgrid Media нет аккаунта, сервера, аналитики и сторонних SDK. Манифест конфиденциальности в App Store заявляет: никакого отслеживания и никаких собираемых данных. Единственное запрашиваемое разрешение — уведомления."),
        ("Сколько стоит Offgrid Media?",
         "Нисколько. Без подписки, без встроенных покупок, без рекламы."),
    ],
    "close_h2": "Ваша медиатека. Ваше устройство. Сигнал не нужен.",
    "close_p": "Offgrid Media бесплатна, для iPhone и iPad, на 11 языках.",
    "close_meta": "Без аккаунта · Без рекламы · Без слежки",
    "stat_langs": "Языков", "stat_zero": "Аккаунтов, рекламы, трекеров",
    "stat_device": "На устройстве", "stat_ios": "iOS, iPhone и iPad",
    "privacy_title": "Политика конфиденциальности — Offgrid Media",
    "privacy_desc": "Offgrid Media не собирает персональные данные. Без аккаунта, без аналитики, без сторонних SDK, без облачной синхронизации.",
    "privacy_h1": "Политика конфиденциальности",
    "privacy_updated": "Обновлено 1 августа 2026 года",
    "privacy_back": "Назад к Offgrid Media",
    "policy": [
        ("p", "<strong>Offgrid Media не собирает, не хранит и не передаёт персональные данные.</strong> Нет аккаунта, нет серверной части, нет аналитики. Ваша медиатека — это файлы на вашем устройстве, и они там и остаются."),
        ("h2", "Что собирает приложение"),
        ("p", "Ничего. Манифест конфиденциальности приложения в App Store заявляет: никакого отслеживания и никаких собираемых типов данных. В приложении нет рекламных идентификаторов, служб отчётов о сбоях и сторонних аналитических или маркетинговых SDK."),
        ("h2", "Где хранятся ваши медиафайлы"),
        ("ul", ["Всё, что вы импортируете, записывается в папку на вашем устройстве. Какую именно — вы выбираете в настройках.",
                "Приложение поддерживает приложение «Файлы», так что те же файлы вы можете просматривать и упорядочивать сами.",
                "Облачной синхронизации и выгрузки нет. Если вы выберете папку, которую синхронизирует iCloud Drive, эту синхронизацию выполняет Apple по вашим настройкам iCloud, а не приложение."]),
        ("h2", "Когда приложение обращается к сети"),
        ("ul", ["<strong>Воспроизведение никогда не использует сеть.</strong> Файлы играют из локального хранилища.",
                "<strong>Добавление по ссылке — использует.</strong> Если вы вставите или отправите ссылку, приложение обратится по этому адресу и к медиасерверу, на который он указывает, по HTTPS, чтобы получить файл. Ничего из этого запроса разработчику не отправляется.",
                "<strong>Ссылки в настройках</strong> открываются в браузере обычным образом."]),
        ("h2", "Разрешения"),
        ("p", "Приложение запрашивает одно разрешение: уведомления, чтобы сообщить, что импорт завершён или не удался. Вы можете отказать — приложение всё равно работает. Импорт из «Фото» использует стандартный системный выбор фотографий, который выполняется вне приложения и не требует доступа к медиатеке."),
        ("h2", "Диагностика"),
        ("p", "В настройках есть локальный журнал активности, чтобы вы видели, что делало приложение. Он никогда не покидает устройство, а записи автоматически удаляются через два дня."),
        ("h2", "Дети"),
        ("p", "Возрастной рейтинг приложения — 4+, и оно не собирает данные ни у кого, включая детей."),
        ("h2", "Этот сайт"),
        ("p", 'Отдельно от приложения: lorenzmaierhofer.com использует <a href="https://plausible.io/privacy-focused-web-analytics" target="_blank" rel="noopener">Plausible Analytics</a> для сводной статистики просмотров. Plausible не устанавливает cookie и не собирает персональные данные. Это касается только сайта — в самом приложении аналитики нет вовсе.'),
        ("h2", "Контент, который вы добавляете"),
        ("p", "Добавляйте только тот контент, который вы вправе хранить. Соблюдение условий использования любой платформы и применимого законодательства — исключительно ваша ответственность."),
        ("h2", "Изменения"),
        ("p", "Если политика изменится, обновлённая версия будет опубликована на этой странице с новой датой."),
        ("h2", "Контакт"),
        ("p", 'Вопросы о конфиденциальности: <a href="mailto:awr9a2npb@mozmail.com">awr9a2npb@mozmail.com</a>'),
    ],
},

"hi": {
    "meta_title": "Offgrid Media – iPhone और iPad के लिए आपकी निजी ऑफ़लाइन मीडिया लाइब्रेरी",
    "meta_desc": "Offgrid Media iPhone और iPad के लिए एक निजी मीडिया लाइब्रेरी है। फ़ाइलों या फ़ोटो से वीडियो और ऑडियो इंपोर्ट करें, फ़ोल्डरों में व्यवस्थित करें और सब कुछ ऑफ़लाइन चलाएँ। कोई खाता नहीं, कोई विज्ञापन नहीं, कोई ट्रैकिंग नहीं।",
    "og_title": "Offgrid Media – आपकी निजी ऑफ़लाइन मीडिया लाइब्रेरी",
    "og_desc": "फ़ाइलों या फ़ोटो से वीडियो और ऑडियो इंपोर्ट करें, फ़ोल्डरों में व्यवस्थित करें और सब कुछ ऑफ़लाइन चलाएँ। डिवाइस पर। बिना खाते के।",
    "og_image_alt": "Offgrid Media – जो आप रखते हैं, सब ऑफ़लाइन",
    "currency": "USD",
    "nav_library": "लाइब्रेरी", "nav_features": "फ़ीचर", "nav_privacy": "निजता",
    "nav_faq": "सवाल-जवाब", "nav_overview": "परिचय",
    "nav_toggle": "मेन्यू खोलें", "theme_toggle": "थीम बदलें",
    "footer_nav": "फ़ुटर", "device": "डिवाइस",
    "h1": "जो आप रखते हैं,|सब ऑफ़लाइन।",
    "cta_soon": "जल्द ही App Store पर", "cta_meta": "मुफ़्त · iPhone और iPad",
    "cta_meta2": "मुफ़्त · iOS 16.1+", "cta_secondary": "यह कैसे काम करता है",
    "cta_live": "App Store से डाउनलोड करें",
    "switch_off": "एयरप्लेन मोड चालू", "switch_on": "एयरप्लेन मोड बंद",
    "hint_off": "आज़माकर देखिए। नेटवर्क बंद है — फिर भी आपकी लाइब्रेरी चल रही है।",
    "hint_on": "नेटवर्क वापस आ गया। आपकी लाइब्रेरी में कुछ नहीं बदला।",
    "chip_network": "नेटवर्क", "chip_no_conn": "कोई कनेक्शन नहीं", "chip_conn": "कनेक्टेड",
    "chip_library": "आपकी लाइब्रेरी", "chip_playing": "चल रहा है",
    "chip_caption": "दोनों ही हाल में एक जैसा। पूरी बात यही है।",
    "video_label": "Offgrid Media की झलक: इंपोर्ट, व्यवस्था और ऑफ़लाइन प्लेबैक",
    "lbl_library": "लाइब्रेरी",
    "h2_library": "आपके अपने मीडिया के लिए एक व्यवस्थित जगह",
    "sub_library": "फ़ोल्डर, खोज और वीडियो या ऑडियो का फ़िल्टर। थंबनेल फ़ाइल से ही बनते हैं, कवर आर्ट और मेटाडेटा सुरक्षित रहते हैं।",
    "lbl_how": "यह कैसे काम करता है", "h2_how": "इंपोर्ट करें, व्यवस्थित करें, चलाएँ",
    "lbl_features": "यह क्या करता है",
    "h2_features": "एक असली प्लेयर, महज़ फ़ाइलों का फ़ोल्डर नहीं",
    "sub_features": "नीचे दी गई हर चीज़ नेटवर्क बंद होने पर भी काम करती है।",
    "h2_privacy": "इकट्ठा करने को कुछ नहीं, क्योंकि भेजने की जगह ही नहीं",
    "sub_privacy": "Offgrid Media का न कोई खाता है, न अपना कोई सर्वर। इसका App Store प्राइवेसी मैनिफ़ेस्ट बताता है: कोई ट्रैकिंग नहीं और कोई डेटा इकट्ठा नहीं।",
    "privacy_items": [
        ("कोई खाता नहीं", "न साइन-अप, न लॉगिन, न प्रोफ़ाइल। ऐप खोलिए और चल पड़ा।"),
        ("ऐप में कोई एनालिटिक्स नहीं", "कोई ट्रैकिंग SDK नहीं, कोई क्रैश रिपोर्टर नहीं, कोई विज्ञापन फ़्रेमवर्क नहीं।"),
        ("कोई क्लाउड सिंक नहीं", "आपकी लाइब्रेरी कहीं अपलोड नहीं होती। न iCloud सिंक, न कोई बैकअप सेवा।"),
        ("एक ही अनुमति", "नोटिफ़िकेशन, ताकि ऐप बता सके कि इंपोर्ट पूरा हुआ। बस यही एक अनुमति माँगी जाती है।"),
    ],
    "privacy_link": "पूरी निजता नीति पढ़ें",
    "lbl_faq": "सवाल", "h2_faq": "अक्सर पूछे जाने वाले सवाल",
    "faq": [
        ("क्या Offgrid Media को इंटरनेट चाहिए?",
         "नहीं। जो एक बार लाइब्रेरी में आ गया, वह आपके डिवाइस पर रहता है और नेटवर्क बंद होने पर भी चलता है। चलाते समय कुछ भी स्ट्रीम नहीं होता, इसलिए न बफ़रिंग है और न ही कोई कनेक्शन टूटने का डर।"),
        ("मेरी फ़ाइलें कहाँ रखी जाती हैं?",
         "आपके डिवाइस पर एक फ़ोल्डर में, ऐप के अपने स्टोरेज के भीतर। सेटिंग्स में आप दूसरा लाइब्रेरी फ़ोल्डर चुन सकते हैं, और चूँकि ऐप iOS की फ़ाइल्स ऐप के साथ काम करता है, वही फ़ाइलें आप वहाँ भी देख सकते हैं। कुछ भी अपलोड नहीं होता और कोई क्लाउड सिंक नहीं है।"),
        ("लाइब्रेरी में मीडिया कैसे जोड़ें?",
         "फ़ाइल्स से इंपोर्ट करें (iCloud Drive या डिवाइस), अपनी फ़ोटो लाइब्रेरी से इंपोर्ट करें, या ऐसे लिंक से जोड़ें जिसे रखने का आपको अधिकार है — उसे ऐप में पेस्ट करें, या अपने ब्राउज़र में शेयर मेनू से Offgrid Media चुनें। इंपोर्ट मुख्य रास्ता है; लिंक से जोड़ना एक अतिरिक्त सुविधा भर है।"),
        ("क्या ऑडियो बैकग्राउंड में चलता रहता है?",
         "हाँ। सेटिंग्स में बैकग्राउंड ऑडियो चालू करें, फिर ऐप बदलने या स्क्रीन लॉक करने पर भी प्लेबैक चलता रहता है — लॉक स्क्रीन और कंट्रोल सेंटर में शीर्षक, कवर और कंट्रोल के साथ। वीडियो पिक्चर इन पिक्चर में दूसरे ऐप के ऊपर तैर सकता है। वीडियो फ़ुल स्क्रीन में भी चलता है, और iPad पर ऐप Split View में दूसरे ऐप के साथ चलता रहता है।"),
        ("क्या ऐप कोई डेटा इकट्ठा करता है?",
         "नहीं। Offgrid Media में न खाता है, न सर्वर, न एनालिटिक्स, न कोई थर्ड-पार्टी SDK। इसका App Store प्राइवेसी मैनिफ़ेस्ट बताता है: कोई ट्रैकिंग नहीं और कोई डेटा इकट्ठा नहीं। सिर्फ़ नोटिफ़िकेशन की अनुमति माँगी जाती है।"),
        ("Offgrid Media की कीमत क्या है?",
         "कुछ नहीं। कोई सब्सक्रिप्शन नहीं, कोई इन-ऐप ख़रीद नहीं, कोई विज्ञापन नहीं।"),
    ],
    "close_h2": "आपकी लाइब्रेरी। आपका डिवाइस। सिग्नल की ज़रूरत नहीं।",
    "close_p": "Offgrid Media मुफ़्त है, iPhone और iPad के लिए, 11 भाषाओं में।",
    "close_meta": "कोई खाता नहीं · कोई विज्ञापन नहीं · कोई ट्रैकिंग नहीं",
    "stat_langs": "भाषाएँ", "stat_zero": "खाते, विज्ञापन, ट्रैकर",
    "stat_device": "डिवाइस पर", "stat_ios": "iOS, iPhone और iPad",
    "privacy_title": "निजता नीति – Offgrid Media",
    "privacy_desc": "Offgrid Media कोई निजी डेटा इकट्ठा नहीं करता। कोई खाता नहीं, कोई एनालिटिक्स नहीं, कोई थर्ड-पार्टी SDK नहीं, कोई क्लाउड सिंक नहीं।",
    "privacy_h1": "निजता नीति",
    "privacy_updated": "अंतिम अद्यतन: 1 अगस्त 2026",
    "privacy_back": "Offgrid Media पर वापस",
    "policy": [
        ("p", "<strong>Offgrid Media कोई भी निजी डेटा इकट्ठा, संग्रहित या प्रेषित नहीं करता।</strong> न कोई खाता है, न कोई सर्वर सेवा, न एनालिटिक्स। आपकी लाइब्रेरी आपके डिवाइस पर रखी फ़ाइलों का समूह है, और वहीं रहती है।"),
        ("h2", "ऐप क्या इकट्ठा करता है"),
        ("p", "कुछ नहीं। ऐप का App Store प्राइवेसी मैनिफ़ेस्ट बताता है कि कोई ट्रैकिंग नहीं और कोई डेटा प्रकार इकट्ठा नहीं किया जाता। ऐप में कोई विज्ञापन पहचानकर्ता, क्रैश रिपोर्टिंग सेवा या थर्ड-पार्टी एनालिटिक्स/मार्केटिंग SDK नहीं है।"),
        ("h2", "आपका मीडिया कहाँ रहता है"),
        ("ul", ["आप जो कुछ इंपोर्ट करते हैं वह आपके डिवाइस के एक फ़ोल्डर में लिखा जाता है। कौन-सा फ़ोल्डर, यह आप सेटिंग्स में चुनते हैं।",
                "ऐप iOS की फ़ाइल्स ऐप के साथ काम करता है, इसलिए वही फ़ाइलें आप ख़ुद देख और प्रबंधित कर सकते हैं।",
                "कोई क्लाउड सिंक नहीं है और किसी तरह का अपलोड नहीं होता। यदि आप ऐसा फ़ोल्डर चुनते हैं जिसे iCloud Drive सिंक करता है, तो वह सिंकिंग आपकी अपनी iCloud सेटिंग्स के तहत Apple करता है, ऐप नहीं।"]),
        ("h2", "ऐप नेटवर्क कब इस्तेमाल करता है"),
        ("ul", ["<strong>प्लेबैक कभी नेटवर्क इस्तेमाल नहीं करता।</strong> फ़ाइलें लोकल स्टोरेज से चलती हैं।",
                "<strong>लिंक से जोड़ने पर करता है।</strong> यदि आप कोई लिंक पेस्ट या शेयर करते हैं, तो ऐप उस पते और उससे जुड़े मीडिया सर्वर से HTTPS पर संपर्क कर फ़ाइल लाता है। इस अनुरोध की कोई जानकारी डेवलपर को नहीं भेजी जाती।",
                "<strong>सेटिंग्स में दिए लिंक</strong> सामान्य रूप से आपके ब्राउज़र में खुलते हैं।"]),
        ("h2", "अनुमतियाँ"),
        ("p", "ऐप एक ही अनुमति माँगता है: नोटिफ़िकेशन, ताकि वह बता सके कि इंपोर्ट पूरा हुआ या विफल रहा। आप मना कर सकते हैं, ऐप फिर भी काम करेगा। फ़ोटो से इंपोर्ट iOS के मानक फ़ोटो पिकर से होता है, जो ऐप के बाहर चलता है और फ़ोटो लाइब्रेरी की अनुमति नहीं माँगता।"),
        ("h2", "डायग्नोस्टिक्स"),
        ("p", "सेटिंग्स में एक लोकल गतिविधि लॉग है ताकि आप देख सकें कि ऐप ने क्या किया। यह कभी आपके डिवाइस से बाहर नहीं जाता और प्रविष्टियाँ दो दिन बाद अपने आप हट जाती हैं।"),
        ("h2", "बच्चे"),
        ("p", "ऐप की रेटिंग 4+ है और यह किसी से भी, बच्चों से भी, कोई डेटा इकट्ठा नहीं करता।"),
        ("h2", "यह वेबसाइट"),
        ("p", 'ऐप से अलग: lorenzmaierhofer.com पेज-व्यू के समग्र आँकड़ों के लिए <a href="https://plausible.io/privacy-focused-web-analytics" target="_blank" rel="noopener">Plausible Analytics</a> इस्तेमाल करती है। Plausible कोई कुकी नहीं रखता और कोई निजी डेटा इकट्ठा नहीं करता। यह केवल वेबसाइट पर लागू है — ऐप में एनालिटिक्स बिल्कुल नहीं है।'),
        ("h2", "आपके जोड़े गए कंटेंट के बारे में"),
        ("p", "कृपया केवल वही सामग्री जोड़ें जिसे रखने का आपको अधिकार है। किसी भी प्लेटफ़ॉर्म की सेवा शर्तों और लागू कानूनों का पालन पूरी तरह आपकी ज़िम्मेदारी है।"),
        ("h2", "बदलाव"),
        ("p", "यदि यह नीति बदलती है, तो अद्यतन संस्करण नई तारीख के साथ इसी पेज पर प्रकाशित किया जाएगा।"),
        ("h2", "संपर्क"),
        ("p", 'निजता से जुड़े सवाल: <a href="mailto:awr9a2npb@mozmail.com">awr9a2npb@mozmail.com</a>'),
    ],
},

"ar": {
    "meta_title": "Offgrid Media – مكتبة الوسائط الشخصية دون اتصال لـ iPhone وiPad",
    "meta_desc": "‏Offgrid Media مكتبة وسائط خاصة لـ iPhone وiPad. استورد الفيديو والصوت من الملفات أو الصور، ونظّمها في مجلدات، وشغّلها كلها دون اتصال. بلا حساب، وبلا إعلانات، وبلا تتبع.",
    "og_title": "Offgrid Media – مكتبة وسائطك الشخصية دون اتصال",
    "og_desc": "استورد الفيديو والصوت من الملفات أو الصور، ونظّمها في مجلدات، وشغّلها كلها دون اتصال. على جهازك. بلا حساب.",
    "og_image_alt": "Offgrid Media – كل ما تحتفظ به، دون اتصال",
    "currency": "SAR",
    "nav_library": "المكتبة", "nav_features": "المزايا", "nav_privacy": "الخصوصية",
    "nav_faq": "الأسئلة", "nav_overview": "نظرة عامة",
    "nav_toggle": "فتح القائمة", "theme_toggle": "تبديل المظهر",
    "footer_nav": "تذييل", "device": "الجهاز",
    "h1": "كل ما تحتفظ به،|دون اتصال.",
    "cta_soon": "قريبًا على App Store", "cta_meta": "مجانًا · iPhone وiPad",
    "cta_meta2": "مجانًا · iOS 16.1+", "cta_secondary": "شاهد كيف يعمل",
    "cta_live": "التنزيل من App Store",
    "switch_off": "وضع الطيران مفعّل", "switch_on": "وضع الطيران متوقف",
    "hint_off": "جرّبه. الشبكة مغلقة — ومكتبتك تعمل رغم ذلك.",
    "hint_on": "عادت الشبكة. لم يتغيّر شيء في مكتبتك.",
    "chip_network": "الشبكة", "chip_no_conn": "لا يوجد اتصال", "chip_conn": "متصل",
    "chip_library": "مكتبتك", "chip_playing": "قيد التشغيل",
    "chip_caption": "الأمر نفسه في الحالتين. وهذا هو بيت القصيد.",
    "video_label": "معاينة Offgrid Media: الاستيراد والتنظيم والتشغيل دون اتصال",
    "lbl_library": "المكتبة",
    "h2_library": "مكان واحد مرتّب للوسائط التي تملكها",
    "sub_library": "مجلدات وبحث وتصفية حسب الفيديو أو الصوت. الصور المصغّرة تُستخرج من الملف نفسه، وتُحفظ صور الأغلفة والبيانات الوصفية.",
    "lbl_how": "كيف يعمل", "h2_how": "استورد، نظّم، شغّل",
    "lbl_features": "ماذا يفعل",
    "h2_features": "مشغّل حقيقي، وليس مجرد مجلد ملفات",
    "sub_features": "كل ما يلي يعمل والشبكة مغلقة.",
    "h2_privacy": "لا شيء يُجمع، لأنه لا توجد جهة تُرسل إليها",
    "sub_privacy": "‏Offgrid Media بلا حساب وبلا خادم خاص به. ويعلن بيان الخصوصية في App Store أنه بلا تتبع وبلا أي بيانات مجمّعة.",
    "privacy_items": [
        ("بلا حساب", "بلا تسجيل، وبلا دخول، وبلا ملف شخصي. افتح التطبيق وسيعمل."),
        ("بلا تحليلات داخل التطبيق", "بلا حزم تتبع، وبلا تقارير أعطال، وبلا أطر إعلانية."),
        ("بلا مزامنة سحابية", "لا تُرفع مكتبتك إلى أي مكان. لا مزامنة iCloud ولا خدمة نسخ احتياطي."),
        ("إذن واحد", "الإشعارات، ليخبرك التطبيق عند انتهاء الاستيراد. وهو الإذن الوحيد الذي يطلبه."),
    ],
    "privacy_link": "اقرأ سياسة الخصوصية كاملة",
    "lbl_faq": "أسئلة", "h2_faq": "الأسئلة الشائعة",
    "faq": [
        ("هل يحتاج Offgrid Media إلى اتصال بالإنترنت؟",
         "لا. بمجرد وصول العنصر إلى مكتبتك يبقى على جهازك ويعمل والشبكة مغلقة. لا يُبث شيء أثناء التشغيل، فلا تحميل مؤقت ولا اتصال يمكن أن ينقطع."),
        ("أين تُحفظ ملفاتي؟",
         "في مجلد على جهازك ضمن مساحة التطبيق. يمكنك اختيار مجلد مكتبة آخر من الإعدادات، ولأن التطبيق يدعم تطبيق الملفات فبإمكانك تصفح الملفات نفسها هناك. لا يُرفع شيء ولا توجد مزامنة سحابية."),
        ("كيف أضيف الوسائط إلى المكتبة؟",
         "الاستيراد من الملفات (iCloud Drive أو الجهاز)، أو الاستيراد من مكتبة الصور، أو الإضافة عبر رابط يحق لك الاحتفاظ به — الصق الرابط داخل التطبيق، أو استخدم قائمة المشاركة في المتصفّح واختر Offgrid Media. الاستيراد هو المسار الأساسي، والإضافة عبر رابط مجرد وسيلة ثانوية."),
        ("هل يستمر الصوت في الخلفية؟",
         "نعم. فعّل الصوت في الخلفية من الإعدادات ليستمر التشغيل عند تبديل التطبيقات أو قفل الشاشة، مع العنوان وصورة الغلاف وعناصر التحكم في شاشة القفل ومركز التحكم. ويمكن للفيديو أن يطفو فوق التطبيقات الأخرى بميزة صورة داخل صورة. كما يعمل الفيديو بملء الشاشة، وعلى iPad يستمر التطبيق بجانب تطبيق آخر في وضع Split View."),
        ("هل يجمع التطبيق أي بيانات؟",
         "لا. ليس لـ Offgrid Media حساب ولا خادم ولا تحليلات ولا حزم طرف ثالث. ويعلن بيان الخصوصية في App Store أنه بلا تتبع وبلا أي بيانات مجمّعة. والإذن الوحيد الذي يطلبه هو الإشعارات."),
        ("كم تبلغ تكلفة Offgrid Media؟",
         "لا شيء. بلا اشتراك، وبلا عمليات شراء داخل التطبيق، وبلا إعلانات."),
    ],
    "close_h2": "مكتبتك. جهازك. بلا حاجة إلى إشارة.",
    "close_p": "‏Offgrid Media مجاني، لـ iPhone وiPad، وبـ 11 لغة.",
    "close_meta": "بلا حساب · بلا إعلانات · بلا تتبع",
    "stat_langs": "لغات", "stat_zero": "حسابات وإعلانات ومتتبعات",
    "stat_device": "على الجهاز", "stat_ios": "‏iOS وiPhone وiPad",
    "privacy_title": "سياسة الخصوصية – Offgrid Media",
    "privacy_desc": "لا يجمع Offgrid Media أي بيانات شخصية. بلا حساب، وبلا تحليلات، وبلا حزم طرف ثالث، وبلا مزامنة سحابية.",
    "privacy_h1": "سياسة الخصوصية",
    "privacy_updated": "آخر تحديث 1 أغسطس 2026",
    "privacy_back": "العودة إلى Offgrid Media",
    "policy": [
        ("p", "<strong>لا يجمع Offgrid Media أي بيانات شخصية ولا يخزّنها ولا ينقلها.</strong> لا يوجد حساب ولا خدمة خادم ولا تحليلات. مكتبتك مجموعة ملفات على جهازك، وتبقى هناك."),
        ("h2", "ما الذي يجمعه التطبيق"),
        ("p", "لا شيء. يعلن بيان الخصوصية الخاص بالتطبيق في App Store أنه بلا تتبع وبلا أي أنواع بيانات مجمّعة. ولا توجد معرّفات إعلانية ولا خدمات تقارير أعطال ولا حزم تحليلات أو تسويق من أطراف أخرى داخل التطبيق."),
        ("h2", "أين توجد وسائطك"),
        ("ul", ["كل ما تستورده يُكتب في مجلد على جهازك. وأنت تختار المجلد من الإعدادات.",
                "يدعم التطبيق تطبيق الملفات، فيمكنك تصفح الملفات نفسها وإدارتها بنفسك.",
                "لا توجد مزامنة سحابية ولا رفع من أي نوع. وإذا اخترت مجلدًا يزامنه iCloud Drive فإن تلك المزامنة تجريها Apple وفق إعدادات iCloud الخاصة بك، وليس التطبيق."]),
        ("h2", "متى يستخدم التطبيق الشبكة"),
        ("ul", ["<strong>التشغيل لا يستخدم الشبكة إطلاقًا.</strong> تُشغَّل الملفات من التخزين المحلي.",
                "<strong>أما الإضافة عبر رابط فتستخدمها.</strong> إذا لصقت رابطًا أو شاركته، يتصل التطبيق بذلك العنوان وبخادم الوسائط الذي يشير إليه عبر HTTPS لجلب الملف. ولا يُرسل أي شيء من هذا الطلب إلى المطوّر.",
                "<strong>الروابط التي تفتحها من الإعدادات</strong> تُفتح في متصفحك كالمعتاد."]),
        ("h2", "الأذونات"),
        ("p", "يطلب التطبيق إذنًا واحدًا: الإشعارات، ليخبرك بانتهاء الاستيراد أو بفشله. ويمكنك رفضه وسيظل التطبيق يعمل. أما الاستيراد من الصور فيستخدم منتقي الصور القياسي في iOS، وهو يعمل خارج التطبيق ولا يتطلب الوصول إلى مكتبة الصور."),
        ("h2", "التشخيص"),
        ("p", "تتضمن الإعدادات سجل نشاط محليًا لتعرف ما فعله التطبيق. ولا يغادر جهازك أبدًا، وتُحذف مدخلاته تلقائيًا بعد يومين."),
        ("h2", "الأطفال"),
        ("p", "تصنيف التطبيق 4+ ولا يجمع بيانات من أي أحد، بمن فيهم الأطفال."),
        ("h2", "هذا الموقع"),
        ("p", 'بمعزل عن التطبيق: يستخدم موقع lorenzmaierhofer.com خدمة <a href="https://plausible.io/privacy-focused-web-analytics" target="_blank" rel="noopener">Plausible Analytics</a> لإحصاءات مشاهدات الصفحات المجمّعة. ولا يضع Plausible أي ملفات تعريف ارتباط ولا يجمع بيانات شخصية. وهذا يخص الموقع فقط، أما التطبيق نفسه فلا يحتوي على أي تحليلات.'),
        ("h2", "المحتوى الذي تضيفه"),
        ("p", "يُرجى إضافة المحتوى الذي يحق لك الاحتفاظ به فقط. والالتزام بشروط خدمة أي منصة وبالقوانين المعمول بها يقع على عاتقك وحدك."),
        ("h2", "التغييرات"),
        ("p", "إذا تغيّرت هذه السياسة فسيُنشر الإصدار المحدَّث على هذه الصفحة بتاريخ جديد."),
        ("h2", "التواصل"),
        ("p", 'أسئلة حول الخصوصية: <a href="mailto:awr9a2npb@mozmail.com">awr9a2npb@mozmail.com</a>'),
    ],
},

"zh": {
    "meta_title": "Offgrid Media – 适用于 iPhone 和 iPad 的私人离线媒体库",
    "meta_desc": "Offgrid Media 是适用于 iPhone 和 iPad 的私人媒体库。从“文件”或“照片”导入视频和音频，用文件夹整理，并全部离线播放。无需账户，没有广告，不做追踪。",
    "og_title": "Offgrid Media – 您的私人离线媒体库",
    "og_desc": "从“文件”或“照片”导入视频和音频，用文件夹整理，并全部离线播放。保存在设备上，无需账户。",
    "og_image_alt": "Offgrid Media – 您保存的一切，离线可用",
    "currency": "CNY",
    "nav_library": "媒体库", "nav_features": "功能", "nav_privacy": "隐私",
    "nav_faq": "常见问题", "nav_overview": "概览",
    "nav_toggle": "打开导航", "theme_toggle": "切换主题",
    "footer_nav": "页脚", "device": "设备",
    "h1": "您保存的一切，|离线可用。",
    "cta_soon": "即将上架 App Store", "cta_meta": "免费 · iPhone 与 iPad",
    "cta_meta2": "免费 · iOS 16.1+", "cta_secondary": "看看它怎么用",
    "cta_live": "在 App Store 下载",
    "switch_off": "飞行模式已开启", "switch_on": "飞行模式已关闭",
    "hint_off": "试试看。网络已断开，您的媒体库照常播放。",
    "hint_on": "网络恢复了。您的媒体库没有任何变化。",
    "chip_network": "网络", "chip_no_conn": "无连接", "chip_conn": "已连接",
    "chip_library": "您的媒体库", "chip_playing": "正在播放",
    "chip_caption": "两种情况完全一样。这正是重点。",
    "video_label": "Offgrid Media 预览：导入、整理与离线播放",
    "lbl_library": "媒体库",
    "h2_library": "属于您自己的媒体，一个整洁的去处",
    "sub_library": "文件夹、搜索，以及按视频或音频筛选。缩略图取自文件本身，封面和元数据都会保留。",
    "lbl_how": "如何使用", "h2_how": "导入、整理、播放",
    "lbl_features": "它能做什么",
    "h2_features": "一个真正的播放器，而不只是一堆文件",
    "sub_features": "下面的一切在断网时同样可用。",
    "h2_privacy": "无从收集，因为根本没有可发送的去处",
    "sub_privacy": "Offgrid Media 没有账户，也没有自己的服务器。它在 App Store 的隐私清单声明：不做追踪，不收集任何数据类型。",
    "privacy_items": [
        ("无需账户", "无需注册、无需登录、没有个人资料。打开就能用。"),
        ("应用内没有分析工具", "没有追踪 SDK，没有崩溃上报，没有广告框架。"),
        ("没有云同步", "您的媒体库不会上传到任何地方。没有 iCloud 同步，也没有备份服务。"),
        ("只要一项权限", "通知权限，用于告诉您导入何时完成。它只会请求这一项。"),
    ],
    "privacy_link": "阅读完整隐私政策",
    "lbl_faq": "问题", "h2_faq": "常见问题",
    "faq": [
        ("Offgrid Media 需要联网吗？",
         "不需要。内容一旦进入媒体库，就保存在您的设备上，断网也能播放。播放时不会串流任何内容，因此没有缓冲，也不存在会中断的连接。"),
        ("我的文件保存在哪里？",
         "保存在您设备上的一个文件夹中，位于应用自己的存储空间内。您可以在设置里另选媒体库文件夹；由于应用支持 iOS“文件”App，您也可以在那里浏览同样的文件。不会上传任何内容，也没有云同步。"),
        ("怎样把媒体添加到媒体库？",
         "从“文件”导入（iCloud Drive 或本机）、从照片图库导入，或通过您有权保存的链接添加——将链接粘贴到应用内，或在浏览器中点“共享”并选择 Offgrid Media。导入是主要方式；通过链接添加只是次要的便捷途径。"),
        ("音频能在后台继续播放吗？",
         "可以。在设置中开启后台音频后，切换应用或锁屏时播放会继续，锁定屏幕和控制中心会显示标题、封面和播放控制。视频还能通过画中画悬浮在其他应用之上。视频也可全屏播放，在 iPad 上还能通过分屏（Split View）与另一个应用并排继续播放。"),
        ("这个应用会收集数据吗？",
         "不会。Offgrid Media 没有账户、没有后端、没有分析工具，也没有第三方 SDK。它在 App Store 的隐私清单声明：不做追踪，不收集任何数据类型。它唯一请求的权限是通知。"),
        ("Offgrid Media 收费吗？",
         "不收费。没有订阅，没有应用内购买，没有广告。"),
    ],
    "close_h2": "您的媒体库。您的设备。不需要信号。",
    "close_p": "Offgrid Media 免费提供，支持 iPhone 和 iPad，共 11 种语言。",
    "close_meta": "无需账户 · 没有广告 · 不做追踪",
    "stat_langs": "种语言", "stat_zero": "账户、广告、追踪器",
    "stat_device": "存于设备", "stat_ios": "iOS、iPhone 与 iPad",
    "privacy_title": "隐私政策 – Offgrid Media",
    "privacy_desc": "Offgrid Media 不收集任何个人数据。没有账户、没有分析工具、没有第三方 SDK、没有云同步。",
    "privacy_h1": "隐私政策",
    "privacy_updated": "最后更新：2026 年 8 月 1 日",
    "privacy_back": "返回 Offgrid Media",
    "policy": [
        ("p", "<strong>Offgrid Media 不收集、不存储、也不传输任何个人数据。</strong>没有账户，没有后端服务，也没有分析工具。您的媒体库就是设备上的一组文件，并且始终留在那里。"),
        ("h2", "应用收集什么"),
        ("p", "什么都不收集。应用在 App Store 的隐私清单声明：不做追踪，不收集任何数据类型。应用中没有广告标识符、没有崩溃上报服务，也没有第三方分析或营销 SDK。"),
        ("h2", "您的媒体存放在哪里"),
        ("ul", ["您导入的所有内容都会写入设备上的一个文件夹。具体是哪个文件夹，由您在设置中选择。",
                "应用支持 iOS“文件”App，因此您可以自行浏览和管理这些文件。",
                "没有云同步，也不会有任何形式的上传。如果您选择了一个由 iCloud Drive 同步的文件夹，那项同步是 Apple 按照您自己的 iCloud 设置完成的，与应用无关。"]),
        ("h2", "应用何时使用网络"),
        ("ul", ["<strong>播放从不使用网络。</strong>文件从本地存储播放。",
                "<strong>通过链接添加时会使用。</strong>如果您粘贴或分享一个链接，应用会通过 HTTPS 访问该地址及其指向的媒体服务器以获取文件。该请求的任何内容都不会发送给开发者。",
                "<strong>您在设置中点按的链接</strong>会照常在浏览器中打开。"]),
        ("h2", "权限"),
        ("p", "应用只请求一项权限：通知，用于告知您导入已完成或失败。您可以拒绝，应用照样可用。从“照片”导入使用 iOS 标准照片选择器，它在应用之外运行，无需访问照片图库。"),
        ("h2", "诊断"),
        ("p", "设置中有一份本地活动日志，方便您了解应用做了什么。它绝不会离开您的设备，且条目会在两天后自动删除。"),
        ("h2", "儿童"),
        ("p", "应用分级为 4+，不会收集任何人的数据，儿童也不例外。"),
        ("h2", "关于本网站"),
        ("p", '与应用无关的一点说明：lorenzmaierhofer.com 使用 <a href="https://plausible.io/privacy-focused-web-analytics" target="_blank" rel="noopener">Plausible Analytics</a> 统计聚合的页面浏览量。Plausible 不设置 Cookie，也不收集个人数据。这只适用于网站——应用本身完全没有任何分析工具。'),
        ("h2", "您添加的内容"),
        ("p", "请仅添加您有权保存的内容。遵守任何平台的服务条款以及适用法律完全是您自己的责任。"),
        ("h2", "变更"),
        ("p", "如果本政策有变更，更新后的版本将连同新日期发布在本页面。"),
        ("h2", "联系方式"),
        ("p", '隐私相关问题：<a href="mailto:awr9a2npb@mozmail.com">awr9a2npb@mozmail.com</a>'),
    ],
},

}
